# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v4_data_player_behavior_friendly_fire import MatchesV4DataPlayerBehaviorFriendlyFire

class TestMatchesV4DataPlayerBehaviorFriendlyFire(unittest.TestCase):
    """MatchesV4DataPlayerBehaviorFriendlyFire unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV4DataPlayerBehaviorFriendlyFire:
        """Test MatchesV4DataPlayerBehaviorFriendlyFire
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV4DataPlayerBehaviorFriendlyFire`
        """
        model = MatchesV4DataPlayerBehaviorFriendlyFire()
        if include_optional:
            return MatchesV4DataPlayerBehaviorFriendlyFire(
                incoming = 1.337,
                outgoing = 1.337
            )
        else:
            return MatchesV4DataPlayerBehaviorFriendlyFire(
                incoming = 1.337,
                outgoing = 1.337,
        )
        """

    def testMatchesV4DataPlayerBehaviorFriendlyFire(self):
        """Test MatchesV4DataPlayerBehaviorFriendlyFire"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
