# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premier_team_v2_response_data import PremierTeamV2ResponseData

class TestPremierTeamV2ResponseData(unittest.TestCase):
    """PremierTeamV2ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremierTeamV2ResponseData:
        """Test PremierTeamV2ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremierTeamV2ResponseData`
        """
        model = PremierTeamV2ResponseData()
        if include_optional:
            return PremierTeamV2ResponseData(
                created_at = '',
                current_season = henrikdev_api_client.models.premier_team_v2_season.PremierTeamV2Season(
                    crest = '', 
                    enrolled = True, 
                    has_earned_prestige = True, 
                    has_earned_promotion_for_next_season = True, 
                    id = '', 
                    name = '', 
                    placement = henrikdev_api_client.models.premier_team_v2_placement.PremierTeamV2Placement(
                        conference = '', 
                        division = 0, 
                        is_provisional = True, 
                        points = 0, ), 
                    promotion_applied = True, 
                    stats = henrikdev_api_client.models.premier_team_v2_stats.PremierTeamV2Stats(
                        losses = 0, 
                        matches = 0, 
                        rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                            lost = 0, 
                            won = 0, ), 
                        wins = 0, ), ),
                customization = henrikdev_api_client.models.premier_team_v1_response_data_customization.PremierTeamV1ResponseDataCustomization(
                    icon = '', 
                    image = '', 
                    primary = '', 
                    secondary = '', 
                    tertiary = '', ),
                id = '',
                member = [
                    henrikdev_api_client.models.premier_team_v2_member.PremierTeamV2Member(
                        joined_at = '', 
                        puuid = '', 
                        role = henrikdev_api_client.models.esports_v2_player_performance_player.EsportsV2PlayerPerformancePlayer(
                            id = 0, 
                            name = '', ), )
                    ],
                name = '',
                seasons = [
                    henrikdev_api_client.models.premier_team_v2_season.PremierTeamV2Season(
                        crest = '', 
                        enrolled = True, 
                        has_earned_prestige = True, 
                        has_earned_promotion_for_next_season = True, 
                        id = '', 
                        name = '', 
                        placement = henrikdev_api_client.models.premier_team_v2_placement.PremierTeamV2Placement(
                            conference = '', 
                            division = 0, 
                            is_provisional = True, 
                            points = 0, ), 
                        promotion_applied = True, 
                        stats = henrikdev_api_client.models.premier_team_v2_stats.PremierTeamV2Stats(
                            losses = 0, 
                            matches = 0, 
                            rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                                lost = 0, 
                                won = 0, ), 
                            wins = 0, ), )
                    ],
                tag = ''
            )
        else:
            return PremierTeamV2ResponseData(
                created_at = '',
                current_season = henrikdev_api_client.models.premier_team_v2_season.PremierTeamV2Season(
                    crest = '', 
                    enrolled = True, 
                    has_earned_prestige = True, 
                    has_earned_promotion_for_next_season = True, 
                    id = '', 
                    name = '', 
                    placement = henrikdev_api_client.models.premier_team_v2_placement.PremierTeamV2Placement(
                        conference = '', 
                        division = 0, 
                        is_provisional = True, 
                        points = 0, ), 
                    promotion_applied = True, 
                    stats = henrikdev_api_client.models.premier_team_v2_stats.PremierTeamV2Stats(
                        losses = 0, 
                        matches = 0, 
                        rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                            lost = 0, 
                            won = 0, ), 
                        wins = 0, ), ),
                customization = henrikdev_api_client.models.premier_team_v1_response_data_customization.PremierTeamV1ResponseDataCustomization(
                    icon = '', 
                    image = '', 
                    primary = '', 
                    secondary = '', 
                    tertiary = '', ),
                id = '',
                member = [
                    henrikdev_api_client.models.premier_team_v2_member.PremierTeamV2Member(
                        joined_at = '', 
                        puuid = '', 
                        role = henrikdev_api_client.models.esports_v2_player_performance_player.EsportsV2PlayerPerformancePlayer(
                            id = 0, 
                            name = '', ), )
                    ],
                name = '',
                seasons = [
                    henrikdev_api_client.models.premier_team_v2_season.PremierTeamV2Season(
                        crest = '', 
                        enrolled = True, 
                        has_earned_prestige = True, 
                        has_earned_promotion_for_next_season = True, 
                        id = '', 
                        name = '', 
                        placement = henrikdev_api_client.models.premier_team_v2_placement.PremierTeamV2Placement(
                            conference = '', 
                            division = 0, 
                            is_provisional = True, 
                            points = 0, ), 
                        promotion_applied = True, 
                        stats = henrikdev_api_client.models.premier_team_v2_stats.PremierTeamV2Stats(
                            losses = 0, 
                            matches = 0, 
                            rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                                lost = 0, 
                                won = 0, ), 
                            wins = 0, ), )
                    ],
                tag = '',
        )
        """

    def testPremierTeamV2ResponseData(self):
        """Test PremierTeamV2ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
