# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v4_data_team import MatchesV4DataTeam

class TestMatchesV4DataTeam(unittest.TestCase):
    """MatchesV4DataTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV4DataTeam:
        """Test MatchesV4DataTeam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV4DataTeam`
        """
        model = MatchesV4DataTeam()
        if include_optional:
            return MatchesV4DataTeam(
                premier_roster = henrikdev_api_client.models.matches_v4_data_team_premier_roster.MatchesV4DataTeamPremierRoster(
                    customization = henrikdev_api_client.models.matches_v2_data_team_roster_customization.MatchesV2DataTeamRosterCustomization(
                        icon = '', 
                        image = '', 
                        primary_color = '', 
                        secondary_color = '', 
                        tertiary_color = '', ), 
                    id = '', 
                    members = [
                        ''
                        ], 
                    name = '', 
                    tag = '', ),
                rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                    lost = 0, 
                    won = 0, ),
                team_id = '',
                won = True
            )
        else:
            return MatchesV4DataTeam(
                rounds = henrikdev_api_client.models.matches_v4_data_team_rounds.MatchesV4DataTeamRounds(
                    lost = 0, 
                    won = 0, ),
                team_id = '',
                won = True,
        )
        """

    def testMatchesV4DataTeam(self):
        """Test MatchesV4DataTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
