# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.website_by_id_v1_response import WebsiteByIdV1Response

class TestWebsiteByIdV1Response(unittest.TestCase):
    """WebsiteByIdV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsiteByIdV1Response:
        """Test WebsiteByIdV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsiteByIdV1Response`
        """
        model = WebsiteByIdV1Response()
        if include_optional:
            return WebsiteByIdV1Response(
                data = henrikdev_api_client.models.website_by_id_v1_data.WebsiteByIdV1Data(
                    banner_url = '', 
                    category = '', 
                    content = '', 
                    date = '', 
                    description = '', 
                    external_link = '', 
                    title = '', 
                    url = '', ),
                status = 0
            )
        else:
            return WebsiteByIdV1Response(
                data = henrikdev_api_client.models.website_by_id_v1_data.WebsiteByIdV1Data(
                    banner_url = '', 
                    category = '', 
                    content = '', 
                    date = '', 
                    description = '', 
                    external_link = '', 
                    title = '', 
                    url = '', ),
                status = 0,
        )
        """

    def testWebsiteByIdV1Response(self):
        """Test WebsiteByIdV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
