# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.queue_status_v1_high_skill import QueueStatusV1HighSkill

class TestQueueStatusV1HighSkill(unittest.TestCase):
    """QueueStatusV1HighSkill unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueStatusV1HighSkill:
        """Test QueueStatusV1HighSkill
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueStatusV1HighSkill`
        """
        model = QueueStatusV1HighSkill()
        if include_optional:
            return QueueStatusV1HighSkill(
                max_party_size = 56,
                max_tier = 56,
                min_tier = 56
            )
        else:
            return QueueStatusV1HighSkill(
                max_party_size = 56,
                max_tier = 56,
                min_tier = 56,
        )
        """

    def testQueueStatusV1HighSkill(self):
        """Test QueueStatusV1HighSkill"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
