# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v2_data_player_behavior import MatchesV2DataPlayerBehavior

class TestMatchesV2DataPlayerBehavior(unittest.TestCase):
    """MatchesV2DataPlayerBehavior unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV2DataPlayerBehavior:
        """Test MatchesV2DataPlayerBehavior
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV2DataPlayerBehavior`
        """
        model = MatchesV2DataPlayerBehavior()
        if include_optional:
            return MatchesV2DataPlayerBehavior(
                afk_rounds = 1.337,
                friendly_fire = henrikdev_api_client.models.matches_v2_data_player_behavior_friendly_fire.MatchesV2DataPlayerBehaviorFriendlyFire(
                    incoming = 1.337, 
                    outgoing = 1.337, ),
                rounds_in_spawn = 1.337
            )
        else:
            return MatchesV2DataPlayerBehavior(
                afk_rounds = 1.337,
                friendly_fire = henrikdev_api_client.models.matches_v2_data_player_behavior_friendly_fire.MatchesV2DataPlayerBehaviorFriendlyFire(
                    incoming = 1.337, 
                    outgoing = 1.337, ),
        )
        """

    def testMatchesV2DataPlayerBehavior(self):
        """Test MatchesV2DataPlayerBehavior"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
