# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v4_data_team_health import MatchesV4DataTeamHealth

class TestMatchesV4DataTeamHealth(unittest.TestCase):
    """MatchesV4DataTeamHealth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV4DataTeamHealth:
        """Test MatchesV4DataTeamHealth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV4DataTeamHealth`
        """
        model = MatchesV4DataTeamHealth()
        if include_optional:
            return MatchesV4DataTeamHealth(
                remaining = 0,
                starting = 0
            )
        else:
            return MatchesV4DataTeamHealth(
                remaining = 0,
                starting = 0,
        )
        """

    def testMatchesV4DataTeamHealth(self):
        """Test MatchesV4DataTeamHealth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
