# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premium_webhook_settings_response import PremiumWebhookSettingsResponse

class TestPremiumWebhookSettingsResponse(unittest.TestCase):
    """PremiumWebhookSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremiumWebhookSettingsResponse:
        """Test PremiumWebhookSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremiumWebhookSettingsResponse`
        """
        model = PremiumWebhookSettingsResponse()
        if include_optional:
            return PremiumWebhookSettingsResponse(
                id = henrikdev_api_client.models.bson_object_id_response.BsonObjectIdResponse(
                    __oid = 'bf325375e030fccba0091731', ),
                created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                    __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                        __number_long = '', ), ),
                enabled = True,
                events = [
                    'MATCH'
                    ],
                match_response_schema = 'v2',
                mmr_history_response_schema = 'v1',
                secret = '',
                updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                    __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                        __number_long = '', ), ),
                url = '',
                userid = ''
            )
        else:
            return PremiumWebhookSettingsResponse(
                created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                    __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                        __number_long = '', ), ),
                enabled = True,
                events = [
                    'MATCH'
                    ],
                match_response_schema = 'v2',
                mmr_history_response_schema = 'v1',
                secret = '',
                updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                    __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                        __number_long = '', ), ),
                url = '',
                userid = '',
        )
        """

    def testPremiumWebhookSettingsResponse(self):
        """Test PremiumWebhookSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
