# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v2_data_round_player_stats_economy import MatchesV2DataRoundPlayerStatsEconomy

class TestMatchesV2DataRoundPlayerStatsEconomy(unittest.TestCase):
    """MatchesV2DataRoundPlayerStatsEconomy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV2DataRoundPlayerStatsEconomy:
        """Test MatchesV2DataRoundPlayerStatsEconomy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV2DataRoundPlayerStatsEconomy`
        """
        model = MatchesV2DataRoundPlayerStatsEconomy()
        if include_optional:
            return MatchesV2DataRoundPlayerStatsEconomy(
                armor = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentArmor(
                    assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_assets_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentAssetsArmor(
                        display_icon = '', ), 
                    id = '', 
                    name = '', ),
                loadout_value = 0,
                remaining = 0,
                spent = 56,
                weapon = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_weapon.MatchesV2DataRoundPlayerStatsEconomyEquipmentWeapon(
                    assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                        display_icon = '', 
                        killfeed_icon = '', ), 
                    id = '', 
                    name = '', )
            )
        else:
            return MatchesV2DataRoundPlayerStatsEconomy(
                armor = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentArmor(
                    assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_assets_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentAssetsArmor(
                        display_icon = '', ), 
                    id = '', 
                    name = '', ),
                loadout_value = 0,
                remaining = 0,
                spent = 56,
                weapon = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_weapon.MatchesV2DataRoundPlayerStatsEconomyEquipmentWeapon(
                    assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                        display_icon = '', 
                        killfeed_icon = '', ), 
                    id = '', 
                    name = '', ),
        )
        """

    def testMatchesV2DataRoundPlayerStatsEconomy(self):
        """Test MatchesV2DataRoundPlayerStatsEconomy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
