# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.valorant_platform import ValorantPlatform

class TestValorantPlatform(unittest.TestCase):
    """ValorantPlatform unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValorantPlatform(self):
        """Test ValorantPlatform"""
        # inst = ValorantPlatform()

if __name__ == '__main__':
    unittest.main()
