# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.raw_v1_payload_values import RawV1PayloadValues

class TestRawV1PayloadValues(unittest.TestCase):
    """RawV1PayloadValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RawV1PayloadValues:
        """Test RawV1PayloadValues
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RawV1PayloadValues`
        """
        model = RawV1PayloadValues()
        if include_optional:
            return RawV1PayloadValues(
            )
        else:
            return RawV1PayloadValues(
        )
        """

    def testRawV1PayloadValues(self):
        """Test RawV1PayloadValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
