# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.mmrv3_peak import MMRV3Peak

class TestMMRV3Peak(unittest.TestCase):
    """MMRV3Peak unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MMRV3Peak:
        """Test MMRV3Peak
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MMRV3Peak`
        """
        model = MMRV3Peak()
        if include_optional:
            return MMRV3Peak(
                ranking_schema = '',
                rr = 56,
                season = henrikdev_api_client.models.season_id_short_combo.SeasonIdShortCombo(
                    id = '', 
                    short = '', ),
                tier = henrikdev_api_client.models.leaderboard_v3_data_threshold_tier.LeaderboardV3DataThresholdTier(
                    id = 56, 
                    name = '', )
            )
        else:
            return MMRV3Peak(
                ranking_schema = '',
                rr = 56,
                season = henrikdev_api_client.models.season_id_short_combo.SeasonIdShortCombo(
                    id = '', 
                    short = '', ),
                tier = henrikdev_api_client.models.leaderboard_v3_data_threshold_tier.LeaderboardV3DataThresholdTier(
                    id = 56, 
                    name = '', ),
        )
        """

    def testMMRV3Peak(self):
        """Test MMRV3Peak"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
