# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.mmrv3_current import MMRV3Current

class TestMMRV3Current(unittest.TestCase):
    """MMRV3Current unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MMRV3Current:
        """Test MMRV3Current
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MMRV3Current`
        """
        model = MMRV3Current()
        if include_optional:
            return MMRV3Current(
                elo = 56,
                games_needed_for_rating = 56,
                last_change = 56,
                leaderboard_placement = henrikdev_api_client.models.mmrv3_leaderboard_placement.MMRV3LeaderboardPlacement(
                    rank = 0, 
                    updated_at = '', ),
                rank_protection_shields = 56,
                rr = 56,
                tier = henrikdev_api_client.models.leaderboard_v3_data_threshold_tier.LeaderboardV3DataThresholdTier(
                    id = 56, 
                    name = '', )
            )
        else:
            return MMRV3Current(
                elo = 56,
                games_needed_for_rating = 56,
                last_change = 56,
                rank_protection_shields = 56,
                rr = 56,
                tier = henrikdev_api_client.models.leaderboard_v3_data_threshold_tier.LeaderboardV3DataThresholdTier(
                    id = 56, 
                    name = '', ),
        )
        """

    def testMMRV3Current(self):
        """Test MMRV3Current"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
