# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premium_webhook_get_data import PremiumWebhookGetData

class TestPremiumWebhookGetData(unittest.TestCase):
    """PremiumWebhookGetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremiumWebhookGetData:
        """Test PremiumWebhookGetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremiumWebhookGetData`
        """
        model = PremiumWebhookGetData()
        if include_optional:
            return PremiumWebhookGetData(
                plan = henrikdev_api_client.models.premium_plan_response.PremiumPlanResponse(
                    _id = null, 
                    active = True, 
                    background_requests_cost = 1.337, 
                    cache_ttl_seconds = 56, 
                    features = [
                        ''
                        ], 
                    id = '', 
                    name = '', 
                    rate_limits = [
                        henrikdev_api_client.models.premium_rate_limit_response.PremiumRateLimitResponse(
                            interval_minutes = 56, 
                            requests = 56, )
                        ], 
                    webhook_poll_interval_seconds = 56, 
                    webhook_user_limit = 56, ),
                settings = henrikdev_api_client.models.premium_webhook_settings_response.PremiumWebhookSettingsResponse(
                    _id = null, 
                    created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                        __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                            __number_long = '', ), ), 
                    enabled = True, 
                    events = [
                        'MATCH'
                        ], 
                    match_response_schema = 'v2', 
                    mmr_history_response_schema = 'v1', 
                    secret = '', 
                    updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                        __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                            __number_long = '', ), ), 
                    url = '', 
                    userid = '', ),
                users = [
                    henrikdev_api_client.models.premium_webhook_enriched_user_response.PremiumWebhookEnrichedUserResponse(
                        _id = null, 
                        created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                            __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                                __number_long = '', ), ), 
                        display_name = '', 
                        display_tag = '', 
                        enabled = True, 
                        events = [
                            'MATCH'
                            ], 
                        last_checked_at = null, 
                        last_match = '', 
                        last_mmr = 56, 
                        puuid = '', 
                        region = '', 
                        updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                            __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                                __number_long = '', ), ), 
                        userid = '', )
                    ]
            )
        else:
            return PremiumWebhookGetData(
                plan = henrikdev_api_client.models.premium_plan_response.PremiumPlanResponse(
                    _id = null, 
                    active = True, 
                    background_requests_cost = 1.337, 
                    cache_ttl_seconds = 56, 
                    features = [
                        ''
                        ], 
                    id = '', 
                    name = '', 
                    rate_limits = [
                        henrikdev_api_client.models.premium_rate_limit_response.PremiumRateLimitResponse(
                            interval_minutes = 56, 
                            requests = 56, )
                        ], 
                    webhook_poll_interval_seconds = 56, 
                    webhook_user_limit = 56, ),
                settings = henrikdev_api_client.models.premium_webhook_settings_response.PremiumWebhookSettingsResponse(
                    _id = null, 
                    created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                        __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                            __number_long = '', ), ), 
                    enabled = True, 
                    events = [
                        'MATCH'
                        ], 
                    match_response_schema = 'v2', 
                    mmr_history_response_schema = 'v1', 
                    secret = '', 
                    updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                        __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                            __number_long = '', ), ), 
                    url = '', 
                    userid = '', ),
                users = [
                    henrikdev_api_client.models.premium_webhook_enriched_user_response.PremiumWebhookEnrichedUserResponse(
                        _id = null, 
                        created_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                            __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                                __number_long = '', ), ), 
                        display_name = '', 
                        display_tag = '', 
                        enabled = True, 
                        events = [
                            'MATCH'
                            ], 
                        last_checked_at = null, 
                        last_match = '', 
                        last_mmr = 56, 
                        puuid = '', 
                        region = '', 
                        updated_at = henrikdev_api_client.models.bson_date_time_response.BsonDateTimeResponse(
                            __date = henrikdev_api_client.models.bson_milliseconds_response.BsonMillisecondsResponse(
                                __number_long = '', ), ), 
                        userid = '', )
                    ],
        )
        """

    def testPremiumWebhookGetData(self):
        """Test PremiumWebhookGetData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
