# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.premier_team_history_v1_response_data import PremierTeamHistoryV1ResponseData

class TestPremierTeamHistoryV1ResponseData(unittest.TestCase):
    """PremierTeamHistoryV1ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PremierTeamHistoryV1ResponseData:
        """Test PremierTeamHistoryV1ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PremierTeamHistoryV1ResponseData`
        """
        model = PremierTeamHistoryV1ResponseData()
        if include_optional:
            return PremierTeamHistoryV1ResponseData(
                league_matches = [
                    henrikdev_api_client.models.premier_team_games_league_string.PremierTeamGamesLeagueString(
                        id = '', 
                        points_after = 56, 
                        points_before = 56, 
                        started_at = '', )
                    ],
                tournament_matches = [
                    henrikdev_api_client.models.premier_team_games_tournament.PremierTeamGamesTournament(
                        matches = [
                            ''
                            ], 
                        placement = 56, 
                        placement_league_bonus = 56, 
                        points_after = 56, 
                        points_before = 56, 
                        tournament_id = '', )
                    ]
            )
        else:
            return PremierTeamHistoryV1ResponseData(
                league_matches = [
                    henrikdev_api_client.models.premier_team_games_league_string.PremierTeamGamesLeagueString(
                        id = '', 
                        points_after = 56, 
                        points_before = 56, 
                        started_at = '', )
                    ],
                tournament_matches = [
                    henrikdev_api_client.models.premier_team_games_tournament.PremierTeamGamesTournament(
                        matches = [
                            ''
                            ], 
                        placement = 56, 
                        placement_league_bonus = 56, 
                        points_after = 56, 
                        points_before = 56, 
                        tournament_id = '', )
                    ],
        )
        """

    def testPremierTeamHistoryV1ResponseData(self):
        """Test PremierTeamHistoryV1ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
