# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.version_v1_data import VersionV1Data

class TestVersionV1Data(unittest.TestCase):
    """VersionV1Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionV1Data:
        """Test VersionV1Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionV1Data`
        """
        model = VersionV1Data()
        if include_optional:
            return VersionV1Data(
                branch = '',
                build_date = '',
                build_ver = '',
                last_checked = '',
                region = '',
                version = 0,
                version_for_api = ''
            )
        else:
            return VersionV1Data(
                branch = '',
                build_date = '',
                build_ver = '',
                last_checked = '',
                region = '',
                version = 0,
                version_for_api = '',
        )
        """

    def testVersionV1Data(self):
        """Test VersionV1Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
