# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v3_list_response_data import MatchesV3ListResponseData

class TestMatchesV3ListResponseData(unittest.TestCase):
    """MatchesV3ListResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV3ListResponseData:
        """Test MatchesV3ListResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV3ListResponseData`
        """
        model = MatchesV3ListResponseData()
        if include_optional:
            return MatchesV3ListResponseData(
                coaches = [
                    henrikdev_api_client.models.matches_v2_data_coach.MatchesV2DataCoach(
                        puuid = '', 
                        team = '', )
                    ],
                is_available = True,
                kills = [
                    henrikdev_api_client.models.matches_v2_data_kill.MatchesV2DataKill(
                        assistants = [
                            henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assistants.MatchesV2DataRoundPlayerStatsKillEventsAssistants(
                                assistant_display_name = '', 
                                assistant_puuid = '', 
                                assistant_team = '', )
                            ], 
                        damage_weapon_assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                            display_icon = '', 
                            killfeed_icon = '', ), 
                        damage_weapon_id = '', 
                        damage_weapon_name = '', 
                        kill_time_in_match = 0, 
                        kill_time_in_round = 0, 
                        killer_display_name = '', 
                        killer_puuid = '', 
                        killer_team = '', 
                        player_locations_on_kill = [
                            henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                    x = 56, 
                                    y = 56, ), 
                                player_display_name = '', 
                                player_puuid = '', 
                                player_team = '', 
                                view_radians = 1.337, )
                            ], 
                        round = 0, 
                        secondary_fire_mode = True, 
                        victim_death_location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                            x = 56, 
                            y = 56, ), 
                        victim_display_name = '', 
                        victim_puuid = '', 
                        victim_team = '', )
                    ],
                metadata = henrikdev_api_client.models.matches_v2_data_metadata.MatchesV2DataMetadata(
                    cluster = '', 
                    game_length = 0, 
                    game_start = 0, 
                    game_start_patched = '', 
                    game_version = '', 
                    map = '', 
                    matchid = '', 
                    mode = '', 
                    mode_id = '', 
                    platform = '', 
                    premier_info = henrikdev_api_client.models.matches_v2_data_metadata_premier_info.MatchesV2DataMetadataPremierInfo(
                        matchup_id = '', 
                        tournament_id = '', ), 
                    queue = '', 
                    region = '', 
                    rounds_played = 0, 
                    season_id = '', ),
                observers = [
                    henrikdev_api_client.models.matches_v2_data_observer.MatchesV2DataObserver(
                        level = 0, 
                        name = '', 
                        party_id = '', 
                        platform = henrikdev_api_client.models.matches_v2_data_platform.MatchesV2DataPlatform(
                            os = henrikdev_api_client.models.matches_v2_data_platform_os.MatchesV2DataPlatformOs(
                                name = '', 
                                version = '', ), 
                            type = '', ), 
                        player_card = '', 
                        player_title = '', 
                        puuid = '', 
                        session_playtime = henrikdev_api_client.models.matches_v2_data_player_session_playtime.MatchesV2DataPlayerSessionPlaytime(
                            milliseconds = 0, 
                            minutes = 0, 
                            seconds = 0, ), 
                        tag = '', 
                        team = '', )
                    ],
                players = henrikdev_api_client.models.matches_v2_data_players.MatchesV2DataPlayers(
                    all_players = [
                        henrikdev_api_client.models.matches_v2_data_player.MatchesV2DataPlayer(
                            ability_casts = henrikdev_api_client.models.matches_v2_data_player_ability_casts.MatchesV2DataPlayerAbilityCasts(
                                c_cast = 0, 
                                e_cast = 0, 
                                q_cast = 0, 
                                x_cast = 0, ), 
                            assets = henrikdev_api_client.models.matches_v2_data_player_assets.MatchesV2DataPlayerAssets(
                                agent = henrikdev_api_client.models.matches_v2_data_player_assets_agent.MatchesV2DataPlayerAssetsAgent(
                                    bust = '', 
                                    full = '', 
                                    killfeed = '', 
                                    small = '', ), 
                                card = henrikdev_api_client.models.matches_v2_data_player_assets_card.MatchesV2DataPlayerAssetsCard(
                                    large = '', 
                                    small = '', 
                                    wide = '', ), ), 
                            behavior = henrikdev_api_client.models.matches_v2_data_player_behavior.MatchesV2DataPlayerBehavior(
                                afk_rounds = 1.337, 
                                friendly_fire = henrikdev_api_client.models.matches_v2_data_player_behavior_friendly_fire.MatchesV2DataPlayerBehaviorFriendlyFire(
                                    incoming = 1.337, 
                                    outgoing = 1.337, ), 
                                rounds_in_spawn = 1.337, ), 
                            character = '', 
                            currenttier = 0, 
                            currenttier_patched = '', 
                            damage_made = 56, 
                            damage_received = 56, 
                            economy = henrikdev_api_client.models.matches_v2_data_player_economy.MatchesV2DataPlayerEconomy(
                                loadout_value = henrikdev_api_client.models.matches_v2_data_player_economy_value.MatchesV2DataPlayerEconomyValue(
                                    average = 1.337, 
                                    overall = 56, ), 
                                spent = henrikdev_api_client.models.matches_v2_data_player_economy_value.MatchesV2DataPlayerEconomyValue(
                                    average = 1.337, 
                                    overall = 56, ), ), 
                            level = 0, 
                            name = '', 
                            party_id = '', 
                            platform = henrikdev_api_client.models.matches_v2_data_platform.MatchesV2DataPlatform(
                                os = henrikdev_api_client.models.matches_v2_data_platform_os.MatchesV2DataPlatformOs(
                                    name = '', 
                                    version = '', ), 
                                type = '', ), 
                            player_card = '', 
                            player_title = '', 
                            puuid = '', 
                            session_playtime = henrikdev_api_client.models.matches_v2_data_player_session_playtime.MatchesV2DataPlayerSessionPlaytime(
                                milliseconds = 0, 
                                minutes = 0, 
                                seconds = 0, ), 
                            stats = henrikdev_api_client.models.matches_v2_data_player_stats.MatchesV2DataPlayerStats(
                                assists = 0, 
                                bodyshots = 0, 
                                deaths = 0, 
                                headshots = 0, 
                                kills = 0, 
                                legshots = 0, 
                                score = 56, ), 
                            tag = '', 
                            team = '', )
                        ], 
                    blue = [
                        henrikdev_api_client.models.matches_v2_data_player.MatchesV2DataPlayer(
                            ability_casts = henrikdev_api_client.models.matches_v2_data_player_ability_casts.MatchesV2DataPlayerAbilityCasts(
                                c_cast = 0, 
                                e_cast = 0, 
                                q_cast = 0, 
                                x_cast = 0, ), 
                            assets = henrikdev_api_client.models.matches_v2_data_player_assets.MatchesV2DataPlayerAssets(
                                agent = henrikdev_api_client.models.matches_v2_data_player_assets_agent.MatchesV2DataPlayerAssetsAgent(
                                    bust = '', 
                                    full = '', 
                                    killfeed = '', 
                                    small = '', ), 
                                card = henrikdev_api_client.models.matches_v2_data_player_assets_card.MatchesV2DataPlayerAssetsCard(
                                    large = '', 
                                    small = '', 
                                    wide = '', ), ), 
                            behavior = henrikdev_api_client.models.matches_v2_data_player_behavior.MatchesV2DataPlayerBehavior(
                                afk_rounds = 1.337, 
                                friendly_fire = henrikdev_api_client.models.matches_v2_data_player_behavior_friendly_fire.MatchesV2DataPlayerBehaviorFriendlyFire(
                                    incoming = 1.337, 
                                    outgoing = 1.337, ), 
                                rounds_in_spawn = 1.337, ), 
                            character = '', 
                            currenttier = 0, 
                            currenttier_patched = '', 
                            damage_made = 56, 
                            damage_received = 56, 
                            economy = henrikdev_api_client.models.matches_v2_data_player_economy.MatchesV2DataPlayerEconomy(
                                loadout_value = , 
                                spent = , ), 
                            level = 0, 
                            name = '', 
                            party_id = '', 
                            platform = henrikdev_api_client.models.matches_v2_data_platform.MatchesV2DataPlatform(
                                os = henrikdev_api_client.models.matches_v2_data_platform_os.MatchesV2DataPlatformOs(
                                    name = '', 
                                    version = '', ), 
                                type = '', ), 
                            player_card = '', 
                            player_title = '', 
                            puuid = '', 
                            session_playtime = henrikdev_api_client.models.matches_v2_data_player_session_playtime.MatchesV2DataPlayerSessionPlaytime(
                                milliseconds = 0, 
                                minutes = 0, 
                                seconds = 0, ), 
                            stats = henrikdev_api_client.models.matches_v2_data_player_stats.MatchesV2DataPlayerStats(
                                assists = 0, 
                                bodyshots = 0, 
                                deaths = 0, 
                                headshots = 0, 
                                kills = 0, 
                                legshots = 0, 
                                score = 56, ), 
                            tag = '', 
                            team = '', )
                        ], 
                    red = [
                        
                        ], ),
                rounds = [
                    henrikdev_api_client.models.matches_v2_data_round.MatchesV2DataRound(
                        bomb_defused = True, 
                        bomb_planted = True, 
                        defuse_events = henrikdev_api_client.models.matches_v2_data_round_defuse_events.MatchesV2DataRoundDefuseEvents(
                            defuse_location = null, 
                            defuse_time_in_round = 0, 
                            defused_by = null, 
                            player_locations_on_defuse = [
                                henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                    location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                        x = 56, 
                                        y = 56, ), 
                                    player_display_name = '', 
                                    player_puuid = '', 
                                    player_team = '', 
                                    view_radians = 1.337, )
                                ], ), 
                        end_type = '', 
                        plant_events = henrikdev_api_client.models.matches_v2_data_round_plant_events.MatchesV2DataRoundPlantEvents(
                            plant_location = null, 
                            plant_site = '', 
                            plant_time_in_round = 0, 
                            planted_by = null, 
                            player_locations_on_plant = [
                                henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                    location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                        x = 56, 
                                        y = 56, ), 
                                    player_display_name = '', 
                                    player_puuid = '', 
                                    player_team = '', 
                                    view_radians = 1.337, )
                                ], ), 
                        player_stats = [
                            henrikdev_api_client.models.matches_v2_data_round_player_stats.MatchesV2DataRoundPlayerStats(
                                ability_casts = henrikdev_api_client.models.matches_v2_data_round_player_stats_ability_casts.MatchesV2DataRoundPlayerStatsAbilityCasts(
                                    c_casts = 0, 
                                    e_casts = 0, 
                                    q_casts = 0, 
                                    x_casts = 0, ), 
                                bodyshots = 0, 
                                damage = 0, 
                                damage_events = [
                                    henrikdev_api_client.models.matches_v2_data_round_player_stats_damage_events.MatchesV2DataRoundPlayerStatsDamageEvents(
                                        bodyshots = 0, 
                                        damage = 0, 
                                        headshots = 0, 
                                        legshots = 0, 
                                        receiver_display_name = '', 
                                        receiver_puuid = '', 
                                        receiver_team = '', )
                                    ], 
                                economy = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy.MatchesV2DataRoundPlayerStatsEconomy(
                                    armor = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentArmor(
                                        assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_assets_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentAssetsArmor(
                                            display_icon = '', ), 
                                        id = '', 
                                        name = '', ), 
                                    loadout_value = 0, 
                                    remaining = 0, 
                                    spent = 56, 
                                    weapon = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_weapon.MatchesV2DataRoundPlayerStatsEconomyEquipmentWeapon(
                                        assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                                            display_icon = '', 
                                            killfeed_icon = '', ), 
                                        id = '', 
                                        name = '', ), ), 
                                headshots = 0, 
                                kill_events = [
                                    henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events.MatchesV2DataRoundPlayerStatsKillEvents(
                                        assistants = [
                                            henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assistants.MatchesV2DataRoundPlayerStatsKillEventsAssistants(
                                                assistant_display_name = '', 
                                                assistant_puuid = '', 
                                                assistant_team = '', )
                                            ], 
                                        damage_weapon_assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                                            display_icon = '', 
                                            killfeed_icon = '', ), 
                                        damage_weapon_id = '', 
                                        damage_weapon_name = '', 
                                        kill_time_in_match = 0, 
                                        kill_time_in_round = 0, 
                                        killer_display_name = '', 
                                        killer_puuid = '', 
                                        killer_team = '', 
                                        player_locations_on_kill = [
                                            
                                            ], 
                                        secondary_fire_mode = True, 
                                        victim_death_location = , 
                                        victim_display_name = '', 
                                        victim_puuid = '', 
                                        victim_team = '', )
                                    ], 
                                kills = 0, 
                                legshots = 0, 
                                player_display_name = '', 
                                player_puuid = '', 
                                player_team = '', 
                                score = 56, 
                                stayed_in_spawn = True, 
                                was_afk = True, 
                                was_penalized = True, )
                            ], 
                        winning_team = '', )
                    ],
                teams = henrikdev_api_client.models.matches_v2_data_teams.MatchesV2DataTeams(
                    blue = henrikdev_api_client.models.matches_v2_data_team.MatchesV2DataTeam(
                        has_won = True, 
                        roster = null, 
                        rounds_lost = 0, 
                        rounds_won = 0, ), 
                    red = henrikdev_api_client.models.matches_v2_data_team.MatchesV2DataTeam(
                        has_won = True, 
                        roster = null, 
                        rounds_lost = 0, 
                        rounds_won = 0, ), )
            )
        else:
            return MatchesV3ListResponseData(
                coaches = [
                    henrikdev_api_client.models.matches_v2_data_coach.MatchesV2DataCoach(
                        puuid = '', 
                        team = '', )
                    ],
                is_available = True,
                kills = [
                    henrikdev_api_client.models.matches_v2_data_kill.MatchesV2DataKill(
                        assistants = [
                            henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assistants.MatchesV2DataRoundPlayerStatsKillEventsAssistants(
                                assistant_display_name = '', 
                                assistant_puuid = '', 
                                assistant_team = '', )
                            ], 
                        damage_weapon_assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                            display_icon = '', 
                            killfeed_icon = '', ), 
                        damage_weapon_id = '', 
                        damage_weapon_name = '', 
                        kill_time_in_match = 0, 
                        kill_time_in_round = 0, 
                        killer_display_name = '', 
                        killer_puuid = '', 
                        killer_team = '', 
                        player_locations_on_kill = [
                            henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                    x = 56, 
                                    y = 56, ), 
                                player_display_name = '', 
                                player_puuid = '', 
                                player_team = '', 
                                view_radians = 1.337, )
                            ], 
                        round = 0, 
                        secondary_fire_mode = True, 
                        victim_death_location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                            x = 56, 
                            y = 56, ), 
                        victim_display_name = '', 
                        victim_puuid = '', 
                        victim_team = '', )
                    ],
                observers = [
                    henrikdev_api_client.models.matches_v2_data_observer.MatchesV2DataObserver(
                        level = 0, 
                        name = '', 
                        party_id = '', 
                        platform = henrikdev_api_client.models.matches_v2_data_platform.MatchesV2DataPlatform(
                            os = henrikdev_api_client.models.matches_v2_data_platform_os.MatchesV2DataPlatformOs(
                                name = '', 
                                version = '', ), 
                            type = '', ), 
                        player_card = '', 
                        player_title = '', 
                        puuid = '', 
                        session_playtime = henrikdev_api_client.models.matches_v2_data_player_session_playtime.MatchesV2DataPlayerSessionPlaytime(
                            milliseconds = 0, 
                            minutes = 0, 
                            seconds = 0, ), 
                        tag = '', 
                        team = '', )
                    ],
                rounds = [
                    henrikdev_api_client.models.matches_v2_data_round.MatchesV2DataRound(
                        bomb_defused = True, 
                        bomb_planted = True, 
                        defuse_events = henrikdev_api_client.models.matches_v2_data_round_defuse_events.MatchesV2DataRoundDefuseEvents(
                            defuse_location = null, 
                            defuse_time_in_round = 0, 
                            defused_by = null, 
                            player_locations_on_defuse = [
                                henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                    location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                        x = 56, 
                                        y = 56, ), 
                                    player_display_name = '', 
                                    player_puuid = '', 
                                    player_team = '', 
                                    view_radians = 1.337, )
                                ], ), 
                        end_type = '', 
                        plant_events = henrikdev_api_client.models.matches_v2_data_round_plant_events.MatchesV2DataRoundPlantEvents(
                            plant_location = null, 
                            plant_site = '', 
                            plant_time_in_round = 0, 
                            planted_by = null, 
                            player_locations_on_plant = [
                                henrikdev_api_client.models.matches_v2_data_round_player_locations_on_event.MatchesV2DataRoundPlayerLocationsOnEvent(
                                    location = henrikdev_api_client.models.matches_v2_data_round_event_location.MatchesV2DataRoundEventLocation(
                                        x = 56, 
                                        y = 56, ), 
                                    player_display_name = '', 
                                    player_puuid = '', 
                                    player_team = '', 
                                    view_radians = 1.337, )
                                ], ), 
                        player_stats = [
                            henrikdev_api_client.models.matches_v2_data_round_player_stats.MatchesV2DataRoundPlayerStats(
                                ability_casts = henrikdev_api_client.models.matches_v2_data_round_player_stats_ability_casts.MatchesV2DataRoundPlayerStatsAbilityCasts(
                                    c_casts = 0, 
                                    e_casts = 0, 
                                    q_casts = 0, 
                                    x_casts = 0, ), 
                                bodyshots = 0, 
                                damage = 0, 
                                damage_events = [
                                    henrikdev_api_client.models.matches_v2_data_round_player_stats_damage_events.MatchesV2DataRoundPlayerStatsDamageEvents(
                                        bodyshots = 0, 
                                        damage = 0, 
                                        headshots = 0, 
                                        legshots = 0, 
                                        receiver_display_name = '', 
                                        receiver_puuid = '', 
                                        receiver_team = '', )
                                    ], 
                                economy = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy.MatchesV2DataRoundPlayerStatsEconomy(
                                    armor = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentArmor(
                                        assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_assets_armor.MatchesV2DataRoundPlayerStatsEconomyEquipmentAssetsArmor(
                                            display_icon = '', ), 
                                        id = '', 
                                        name = '', ), 
                                    loadout_value = 0, 
                                    remaining = 0, 
                                    spent = 56, 
                                    weapon = henrikdev_api_client.models.matches_v2_data_round_player_stats_economy_equipment_weapon.MatchesV2DataRoundPlayerStatsEconomyEquipmentWeapon(
                                        assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                                            display_icon = '', 
                                            killfeed_icon = '', ), 
                                        id = '', 
                                        name = '', ), ), 
                                headshots = 0, 
                                kill_events = [
                                    henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events.MatchesV2DataRoundPlayerStatsKillEvents(
                                        assistants = [
                                            henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assistants.MatchesV2DataRoundPlayerStatsKillEventsAssistants(
                                                assistant_display_name = '', 
                                                assistant_puuid = '', 
                                                assistant_team = '', )
                                            ], 
                                        damage_weapon_assets = henrikdev_api_client.models.matches_v2_data_round_player_stats_kill_events_assets.MatchesV2DataRoundPlayerStatsKillEventsAssets(
                                            display_icon = '', 
                                            killfeed_icon = '', ), 
                                        damage_weapon_id = '', 
                                        damage_weapon_name = '', 
                                        kill_time_in_match = 0, 
                                        kill_time_in_round = 0, 
                                        killer_display_name = '', 
                                        killer_puuid = '', 
                                        killer_team = '', 
                                        player_locations_on_kill = [
                                            
                                            ], 
                                        secondary_fire_mode = True, 
                                        victim_death_location = , 
                                        victim_display_name = '', 
                                        victim_puuid = '', 
                                        victim_team = '', )
                                    ], 
                                kills = 0, 
                                legshots = 0, 
                                player_display_name = '', 
                                player_puuid = '', 
                                player_team = '', 
                                score = 56, 
                                stayed_in_spawn = True, 
                                was_afk = True, 
                                was_penalized = True, )
                            ], 
                        winning_team = '', )
                    ],
        )
        """

    def testMatchesV3ListResponseData(self):
        """Test MatchesV3ListResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
