# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev-api-client.models.agent_id_name_combo import AgentIdNameCombo

class TestAgentIdNameCombo(unittest.TestCase):
    """AgentIdNameCombo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentIdNameCombo:
        """Test AgentIdNameCombo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentIdNameCombo`
        """
        model = AgentIdNameCombo()
        if include_optional:
            return AgentIdNameCombo(
                id = '',
                name = ''
            )
        else:
            return AgentIdNameCombo(
                id = '',
                name = '',
        )
        """

    def testAgentIdNameCombo(self):
        """Test AgentIdNameCombo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
