# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.esports_v2_event_status import EsportsV2EventStatus

class TestEsportsV2EventStatus(unittest.TestCase):
    """EsportsV2EventStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsportsV2EventStatus(self):
        """Test EsportsV2EventStatus"""
        # inst = EsportsV2EventStatus()

if __name__ == '__main__':
    unittest.main()
