# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.matches_v4_data_player_performance import MatchesV4DataPlayerPerformance

class TestMatchesV4DataPlayerPerformance(unittest.TestCase):
    """MatchesV4DataPlayerPerformance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchesV4DataPlayerPerformance:
        """Test MatchesV4DataPlayerPerformance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchesV4DataPlayerPerformance`
        """
        model = MatchesV4DataPlayerPerformance()
        if include_optional:
            return MatchesV4DataPlayerPerformance(
                breakdown = henrikdev_api_client.models.matches_v4_data_player_performance_breakdown.MatchesV4DataPlayerPerformanceBreakdown(
                    adjusted_deaths = -1.5, 
                    adjusted_kills = 1.337, 
                    assists = 1.337, 
                    damage = 1.337, 
                    defuses = 1.337, 
                    plants = 1.337, 
                    trades = 1.337, 
                    utility_usage = 1.337, ),
                ratings = henrikdev_api_client.models.matches_v4_data_player_performance_ratings.MatchesV4DataPlayerPerformanceRatings(
                    combat = null, 
                    grade = '', 
                    utility = null, ),
                score = 1.337
            )
        else:
            return MatchesV4DataPlayerPerformance(
                breakdown = henrikdev_api_client.models.matches_v4_data_player_performance_breakdown.MatchesV4DataPlayerPerformanceBreakdown(
                    adjusted_deaths = -1.5, 
                    adjusted_kills = 1.337, 
                    assists = 1.337, 
                    damage = 1.337, 
                    defuses = 1.337, 
                    plants = 1.337, 
                    trades = 1.337, 
                    utility_usage = 1.337, ),
        )
        """

    def testMatchesV4DataPlayerPerformance(self):
        """Test MatchesV4DataPlayerPerformance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
