# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.stored_match_stats_damage import StoredMatchStatsDamage

class TestStoredMatchStatsDamage(unittest.TestCase):
    """StoredMatchStatsDamage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoredMatchStatsDamage:
        """Test StoredMatchStatsDamage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoredMatchStatsDamage`
        """
        model = StoredMatchStatsDamage()
        if include_optional:
            return StoredMatchStatsDamage(
                made = 56,
                received = 56
            )
        else:
            return StoredMatchStatsDamage(
                made = 56,
                received = 56,
        )
        """

    def testStoredMatchStatsDamage(self):
        """Test StoredMatchStatsDamage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
