# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.accolades_v1_summary import AccoladesV1Summary

class TestAccoladesV1Summary(unittest.TestCase):
    """AccoladesV1Summary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccoladesV1Summary:
        """Test AccoladesV1Summary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccoladesV1Summary`
        """
        model = AccoladesV1Summary()
        if include_optional:
            return AccoladesV1Summary(
                all_time = [
                    henrikdev_api_client.models.accolades_v1_summary_metric.AccoladesV1SummaryMetric(
                        best_value = 1.337, 
                        count = 0, 
                        id = '', 
                        type = null, )
                    ],
                seasons = [
                    henrikdev_api_client.models.accolades_v1_season.AccoladesV1Season(
                        accolades = [
                            henrikdev_api_client.models.accolades_v1_summary_metric.AccoladesV1SummaryMetric(
                                best_value = 1.337, 
                                count = 0, 
                                id = '', 
                                type = null, )
                            ], 
                        season = henrikdev_api_client.models.accolades_v1_season_id.AccoladesV1SeasonId(
                            id = '', 
                            short = '', ), )
                    ]
            )
        else:
            return AccoladesV1Summary(
                all_time = [
                    henrikdev_api_client.models.accolades_v1_summary_metric.AccoladesV1SummaryMetric(
                        best_value = 1.337, 
                        count = 0, 
                        id = '', 
                        type = null, )
                    ],
                seasons = [
                    henrikdev_api_client.models.accolades_v1_season.AccoladesV1Season(
                        accolades = [
                            henrikdev_api_client.models.accolades_v1_summary_metric.AccoladesV1SummaryMetric(
                                best_value = 1.337, 
                                count = 0, 
                                id = '', 
                                type = null, )
                            ], 
                        season = henrikdev_api_client.models.accolades_v1_season_id.AccoladesV1SeasonId(
                            id = '', 
                            short = '', ), )
                    ],
        )
        """

    def testAccoladesV1Summary(self):
        """Test AccoladesV1Summary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
