# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.esports_v2_match_performance import EsportsV2MatchPerformance

class TestEsportsV2MatchPerformance(unittest.TestCase):
    """EsportsV2MatchPerformance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsportsV2MatchPerformance:
        """Test EsportsV2MatchPerformance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsportsV2MatchPerformance`
        """
        model = EsportsV2MatchPerformance()
        if include_optional:
            return EsportsV2MatchPerformance(
                kill_matrix = [
                    henrikdev_api_client.models.esports_v2_kill_matrix_entry.EsportsV2KillMatrixEntry(
                        deaths = 0, 
                        killer = 0, 
                        kills = 0, 
                        victim = 0, )
                    ],
                player_performances = [
                    henrikdev_api_client.models.esports_v2_player_performance.EsportsV2PlayerPerformance(
                        clutches = henrikdev_api_client.models.esports_v2_player_performance_clutches.EsportsV2PlayerPerformanceClutches(
                            1v1 = 0, 
                            1v2 = 0, 
                            1v3 = 0, 
                            1v4 = 0, 
                            1v5 = 0, ), 
                        defuses = 0, 
                        econ_rating = 0, 
                        multi_kills = henrikdev_api_client.models.esports_v2_player_performance_multi_kills.EsportsV2PlayerPerformanceMultiKills(
                            2k = 0, 
                            3k = 0, 
                            4k = 0, 
                            5k = 0, ), 
                        plants = 0, 
                        player = henrikdev_api_client.models.esports_v2_player_performance_player.EsportsV2PlayerPerformancePlayer(
                            id = 0, 
                            name = '', ), )
                    ]
            )
        else:
            return EsportsV2MatchPerformance(
                kill_matrix = [
                    henrikdev_api_client.models.esports_v2_kill_matrix_entry.EsportsV2KillMatrixEntry(
                        deaths = 0, 
                        killer = 0, 
                        kills = 0, 
                        victim = 0, )
                    ],
                player_performances = [
                    henrikdev_api_client.models.esports_v2_player_performance.EsportsV2PlayerPerformance(
                        clutches = henrikdev_api_client.models.esports_v2_player_performance_clutches.EsportsV2PlayerPerformanceClutches(
                            1v1 = 0, 
                            1v2 = 0, 
                            1v3 = 0, 
                            1v4 = 0, 
                            1v5 = 0, ), 
                        defuses = 0, 
                        econ_rating = 0, 
                        multi_kills = henrikdev_api_client.models.esports_v2_player_performance_multi_kills.EsportsV2PlayerPerformanceMultiKills(
                            2k = 0, 
                            3k = 0, 
                            4k = 0, 
                            5k = 0, ), 
                        plants = 0, 
                        player = henrikdev_api_client.models.esports_v2_player_performance_player.EsportsV2PlayerPerformancePlayer(
                            id = 0, 
                            name = '', ), )
                    ],
        )
        """

    def testEsportsV2MatchPerformance(self):
        """Test EsportsV2MatchPerformance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
