# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from henrikdev_api_client.models.esports_v2_match_game_player import EsportsV2MatchGamePlayer

class TestEsportsV2MatchGamePlayer(unittest.TestCase):
    """EsportsV2MatchGamePlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsportsV2MatchGamePlayer:
        """Test EsportsV2MatchGamePlayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsportsV2MatchGamePlayer`
        """
        model = EsportsV2MatchGamePlayer()
        if include_optional:
            return EsportsV2MatchGamePlayer(
                agent = '',
                player = henrikdev_api_client.models.esports_v2_match_player.EsportsV2MatchPlayer(
                    id = 0, 
                    name = '', 
                    nation = '', 
                    slug = '', ),
                stats = henrikdev_api_client.models.esports_v2_match_game_player_stats.EsportsV2MatchGamePlayerStats(
                    acs = 0, 
                    adr = 1.337, 
                    assists = 0, 
                    deaths = 0, 
                    first_deaths = 0, 
                    first_kills = 0, 
                    fk_diff = 56, 
                    hs_pct = 1.337, 
                    kast = 1.337, 
                    kd_diff = 56, 
                    kills = 0, 
                    rating = 1.337, )
            )
        else:
            return EsportsV2MatchGamePlayer(
                agent = '',
                player = henrikdev_api_client.models.esports_v2_match_player.EsportsV2MatchPlayer(
                    id = 0, 
                    name = '', 
                    nation = '', 
                    slug = '', ),
                stats = henrikdev_api_client.models.esports_v2_match_game_player_stats.EsportsV2MatchGamePlayerStats(
                    acs = 0, 
                    adr = 1.337, 
                    assists = 0, 
                    deaths = 0, 
                    first_deaths = 0, 
                    first_kills = 0, 
                    fk_diff = 56, 
                    hs_pct = 1.337, 
                    kast = 1.337, 
                    kd_diff = 56, 
                    kills = 0, 
                    rating = 1.337, ),
        )
        """

    def testEsportsV2MatchGamePlayer(self):
        """Test EsportsV2MatchGamePlayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
