/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.AccoladesV1Player
import henrikdevApiClient.models.AccoladesV1MatchMetric

class AccoladesV1PlayerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccoladesV1Player
        //val modelInstance = AccoladesV1Player()

        // to test the property `accolades`
        should("test accolades") {
            // uncomment below to test the property
            //modelInstance.accolades shouldBe ("TODO")
        }

        // to test the property `puuid`
        should("test puuid") {
            // uncomment below to test the property
            //modelInstance.puuid shouldBe ("TODO")
        }

    }
}
