/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.AgentMasteryV1Flourish

class AgentMasteryV1FlourishTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgentMasteryV1Flourish
        //val modelInstance = AgentMasteryV1Flourish()

        // to test the property `longLevel`
        should("test longLevel") {
            // uncomment below to test the property
            //modelInstance.longLevel shouldBe ("TODO")
        }

        // to test the property `shortLevel`
        should("test shortLevel") {
            // uncomment below to test the property
            //modelInstance.shortLevel shouldBe ("TODO")
        }

    }
}
