/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.BundleItem
import henrikdevApiClient.models.Item

class BundleItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BundleItem
        //val modelInstance = BundleItem()

        // to test the property `basePrice`
        should("test basePrice") {
            // uncomment below to test the property
            //modelInstance.basePrice shouldBe ("TODO")
        }

        // to test the property `currencyID`
        should("test currencyID") {
            // uncomment below to test the property
            //modelInstance.currencyID shouldBe ("TODO")
        }

        // to test the property `discountPercent`
        should("test discountPercent") {
            // uncomment below to test the property
            //modelInstance.discountPercent shouldBe ("TODO")
        }

        // to test the property `discountedPrice`
        should("test discountedPrice") {
            // uncomment below to test the property
            //modelInstance.discountedPrice shouldBe ("TODO")
        }

        // to test the property `isPromoItem`
        should("test isPromoItem") {
            // uncomment below to test the property
            //modelInstance.isPromoItem shouldBe ("TODO")
        }

        // to test the property `item`
        should("test item") {
            // uncomment below to test the property
            //modelInstance.item shouldBe ("TODO")
        }

    }
}
