/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.EsportsV2HeadToHeadScore

class EsportsV2HeadToHeadScoreTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EsportsV2HeadToHeadScore
        //val modelInstance = EsportsV2HeadToHeadScore()

        // to test the property `team1`
        should("test team1") {
            // uncomment below to test the property
            //modelInstance.team1 shouldBe ("TODO")
        }

        // to test the property `team2`
        should("test team2") {
            // uncomment below to test the property
            //modelInstance.team2 shouldBe ("TODO")
        }

        // to test the property `winnerTeam`
        should("test winnerTeam") {
            // uncomment below to test the property
            //modelInstance.winnerTeam shouldBe ("TODO")
        }

    }
}
