/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.EsportsV2AgentUsage

class EsportsV2AgentUsageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EsportsV2AgentUsage
        //val modelInstance = EsportsV2AgentUsage()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `percentage`
        should("test percentage") {
            // uncomment below to test the property
            //modelInstance.percentage shouldBe ("TODO")
        }

        // to test the property `rounds`
        should("test rounds") {
            // uncomment below to test the property
            //modelInstance.rounds shouldBe ("TODO")
        }

    }
}
