/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.EsportsV2TeamEconomy
import henrikdevApiClient.models.EsportsV2TeamEconomyRoundWon

class EsportsV2TeamEconomyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EsportsV2TeamEconomy
        //val modelInstance = EsportsV2TeamEconomy()

        // to test the property `eco`
        should("test eco") {
            // uncomment below to test the property
            //modelInstance.eco shouldBe ("TODO")
        }

        // to test the property `fullBuy`
        should("test fullBuy") {
            // uncomment below to test the property
            //modelInstance.fullBuy shouldBe ("TODO")
        }

        // to test the property `pistolWon`
        should("test pistolWon") {
            // uncomment below to test the property
            //modelInstance.pistolWon shouldBe ("TODO")
        }

        // to test the property `semiEco`
        should("test semiEco") {
            // uncomment below to test the property
            //modelInstance.semiEco shouldBe ("TODO")
        }

        // to test the property `teamName`
        should("test teamName") {
            // uncomment below to test the property
            //modelInstance.teamName shouldBe ("TODO")
        }

    }
}
