/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.EsportsV2PlayerPerformanceClutches

class EsportsV2PlayerPerformanceClutchesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EsportsV2PlayerPerformanceClutches
        //val modelInstance = EsportsV2PlayerPerformanceClutches()

        // to test the property ``1v1``
        should("test `1v1`") {
            // uncomment below to test the property
            //modelInstance.`1v1` shouldBe ("TODO")
        }

        // to test the property ``1v2``
        should("test `1v2`") {
            // uncomment below to test the property
            //modelInstance.`1v2` shouldBe ("TODO")
        }

        // to test the property ``1v3``
        should("test `1v3`") {
            // uncomment below to test the property
            //modelInstance.`1v3` shouldBe ("TODO")
        }

        // to test the property ``1v4``
        should("test `1v4`") {
            // uncomment below to test the property
            //modelInstance.`1v4` shouldBe ("TODO")
        }

        // to test the property ``1v5``
        should("test `1v5`") {
            // uncomment below to test the property
            //modelInstance.`1v5` shouldBe ("TODO")
        }

    }
}
