/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.MatchesV2DataRoundPlayer

class MatchesV2DataRoundPlayerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchesV2DataRoundPlayer
        //val modelInstance = MatchesV2DataRoundPlayer()

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `puuid`
        should("test puuid") {
            // uncomment below to test the property
            //modelInstance.puuid shouldBe ("TODO")
        }

        // to test the property `team`
        should("test team") {
            // uncomment below to test the property
            //modelInstance.team shouldBe ("TODO")
        }

    }
}
