/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.MatchesV4DataRound
import henrikdevApiClient.models.MatchesV4DataRoundDefuse
import henrikdevApiClient.models.MatchesV4DataRoundPlant
import henrikdevApiClient.models.MatchesV4DataRoundPlayerStats

class MatchesV4DataRoundTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchesV4DataRound
        //val modelInstance = MatchesV4DataRound()

        // to test the property `ceremony`
        should("test ceremony") {
            // uncomment below to test the property
            //modelInstance.ceremony shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `stats`
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

        // to test the property `winningTeam`
        should("test winningTeam") {
            // uncomment below to test the property
            //modelInstance.winningTeam shouldBe ("TODO")
        }

        // to test the property `defuse`
        should("test defuse") {
            // uncomment below to test the property
            //modelInstance.defuse shouldBe ("TODO")
        }

        // to test the property `plant`
        should("test plant") {
            // uncomment below to test the property
            //modelInstance.plant shouldBe ("TODO")
        }

    }
}
