/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.MatchesV2DataRoundPlayerStatsKillEventsAssistants

class MatchesV2DataRoundPlayerStatsKillEventsAssistantsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchesV2DataRoundPlayerStatsKillEventsAssistants
        //val modelInstance = MatchesV2DataRoundPlayerStatsKillEventsAssistants()

        // to test the property `assistantDisplayName`
        should("test assistantDisplayName") {
            // uncomment below to test the property
            //modelInstance.assistantDisplayName shouldBe ("TODO")
        }

        // to test the property `assistantPuuid`
        should("test assistantPuuid") {
            // uncomment below to test the property
            //modelInstance.assistantPuuid shouldBe ("TODO")
        }

        // to test the property `assistantTeam`
        should("test assistantTeam") {
            // uncomment below to test the property
            //modelInstance.assistantTeam shouldBe ("TODO")
        }

    }
}
