/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.MatchesV4DataPlayerPerformanceUtilityRatings

class MatchesV4DataPlayerPerformanceUtilityRatingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MatchesV4DataPlayerPerformanceUtilityRatings
        //val modelInstance = MatchesV4DataPlayerPerformanceUtilityRatings()

        // to test the property `assists`
        should("test assists") {
            // uncomment below to test the property
            //modelInstance.assists shouldBe ("TODO")
        }

        // to test the property `defuses`
        should("test defuses") {
            // uncomment below to test the property
            //modelInstance.defuses shouldBe ("TODO")
        }

        // to test the property `plants`
        should("test plants") {
            // uncomment below to test the property
            //modelInstance.plants shouldBe ("TODO")
        }

        // to test the property `utilityUsage`
        should("test utilityUsage") {
            // uncomment below to test the property
            //modelInstance.utilityUsage shouldBe ("TODO")
        }

    }
}
