/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.PremierTeamV1ResponseDataPlacement

class PremierTeamV1ResponseDataPlacementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremierTeamV1ResponseDataPlacement
        //val modelInstance = PremierTeamV1ResponseDataPlacement()

        // to test the property `conference`
        should("test conference") {
            // uncomment below to test the property
            //modelInstance.conference shouldBe ("TODO")
        }

        // to test the property `division`
        should("test division") {
            // uncomment below to test the property
            //modelInstance.division shouldBe ("TODO")
        }

        // to test the property `place`
        should("test place") {
            // uncomment below to test the property
            //modelInstance.place shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

    }
}
