/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.PremiumPlanResponse
import henrikdevApiClient.models.BsonObjectIdResponse
import henrikdevApiClient.models.PremiumRateLimitResponse

class PremiumPlanResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremiumPlanResponse
        //val modelInstance = PremiumPlanResponse()

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `backgroundRequestsCost`
        should("test backgroundRequestsCost") {
            // uncomment below to test the property
            //modelInstance.backgroundRequestsCost shouldBe ("TODO")
        }

        // to test the property `cacheTtlSeconds`
        should("test cacheTtlSeconds") {
            // uncomment below to test the property
            //modelInstance.cacheTtlSeconds shouldBe ("TODO")
        }

        // to test the property `features`
        should("test features") {
            // uncomment below to test the property
            //modelInstance.features shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `rateLimits`
        should("test rateLimits") {
            // uncomment below to test the property
            //modelInstance.rateLimits shouldBe ("TODO")
        }

        // to test the property `webhookPollIntervalSeconds`
        should("test webhookPollIntervalSeconds") {
            // uncomment below to test the property
            //modelInstance.webhookPollIntervalSeconds shouldBe ("TODO")
        }

        // to test the property `webhookUserLimit`
        should("test webhookUserLimit") {
            // uncomment below to test the property
            //modelInstance.webhookUserLimit shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
