/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.PremierTeamV2Placement

class PremierTeamV2PlacementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremierTeamV2Placement
        //val modelInstance = PremierTeamV2Placement()

        // to test the property `conference`
        should("test conference") {
            // uncomment below to test the property
            //modelInstance.conference shouldBe ("TODO")
        }

        // to test the property `division`
        should("test division") {
            // uncomment below to test the property
            //modelInstance.division shouldBe ("TODO")
        }

        // to test the property `isProvisional`
        should("test isProvisional") {
            // uncomment below to test the property
            //modelInstance.isProvisional shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

    }
}
