/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.PremierTeamHistoryV1ResponseData
import henrikdevApiClient.models.PremierTeamGamesLeagueString
import henrikdevApiClient.models.PremierTeamGamesTournament

class PremierTeamHistoryV1ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremierTeamHistoryV1ResponseData
        //val modelInstance = PremierTeamHistoryV1ResponseData()

        // to test the property `leagueMatches`
        should("test leagueMatches") {
            // uncomment below to test the property
            //modelInstance.leagueMatches shouldBe ("TODO")
        }

        // to test the property `tournamentMatches`
        should("test tournamentMatches") {
            // uncomment below to test the property
            //modelInstance.tournamentMatches shouldBe ("TODO")
        }

    }
}
