/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.SeasonIdShortCombo

class SeasonIdShortComboTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SeasonIdShortCombo
        //val modelInstance = SeasonIdShortCombo()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `short`
        should("test short") {
            // uncomment below to test the property
            //modelInstance.short shouldBe ("TODO")
        }

    }
}
