/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.StatusIncident
import henrikdevApiClient.models.StatusIncidentContent
import henrikdevApiClient.models.StatusIncidentUpdate

class StatusIncidentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusIncident
        //val modelInstance = StatusIncident()

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `incidentSeverity`
        should("test incidentSeverity") {
            // uncomment below to test the property
            //modelInstance.incidentSeverity shouldBe ("TODO")
        }

        // to test the property `platforms`
        should("test platforms") {
            // uncomment below to test the property
            //modelInstance.platforms shouldBe ("TODO")
        }

        // to test the property `titles`
        should("test titles") {
            // uncomment below to test the property
            //modelInstance.titles shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `updates`
        should("test updates") {
            // uncomment below to test the property
            //modelInstance.updates shouldBe ("TODO")
        }

        // to test the property `archiveAt`
        should("test archiveAt") {
            // uncomment below to test the property
            //modelInstance.archiveAt shouldBe ("TODO")
        }

        // to test the property `maintenanceStatus`
        should("test maintenanceStatus") {
            // uncomment below to test the property
            //modelInstance.maintenanceStatus shouldBe ("TODO")
        }

    }
}
