/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.StoredMatchMeta
import henrikdevApiClient.models.StoredMatchMetaMap
import henrikdevApiClient.models.StoredMatchMetaSeason

class StoredMatchMetaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StoredMatchMeta
        //val modelInstance = StoredMatchMeta()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `map`
        should("test map") {
            // uncomment below to test the property
            //modelInstance.map shouldBe ("TODO")
        }

        // to test the property `mode`
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `region`
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `season`
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

        // to test the property `startedAt`
        should("test startedAt") {
            // uncomment below to test the property
            //modelInstance.startedAt shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `cluster`
        should("test cluster") {
            // uncomment below to test the property
            //modelInstance.cluster shouldBe ("TODO")
        }

    }
}
