/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.StoredMatchStats
import henrikdevApiClient.models.StoredMatchStatsCharacter
import henrikdevApiClient.models.StoredMatchStatsDamage
import henrikdevApiClient.models.StoredMatchStatsShots

class StoredMatchStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StoredMatchStats
        //val modelInstance = StoredMatchStats()

        // to test the property `assists`
        should("test assists") {
            // uncomment below to test the property
            //modelInstance.assists shouldBe ("TODO")
        }

        // to test the property `character`
        should("test character") {
            // uncomment below to test the property
            //modelInstance.character shouldBe ("TODO")
        }

        // to test the property `damage`
        should("test damage") {
            // uncomment below to test the property
            //modelInstance.damage shouldBe ("TODO")
        }

        // to test the property `deaths`
        should("test deaths") {
            // uncomment below to test the property
            //modelInstance.deaths shouldBe ("TODO")
        }

        // to test the property `kills`
        should("test kills") {
            // uncomment below to test the property
            //modelInstance.kills shouldBe ("TODO")
        }

        // to test the property `level`
        should("test level") {
            // uncomment below to test the property
            //modelInstance.level shouldBe ("TODO")
        }

        // to test the property `puuid`
        should("test puuid") {
            // uncomment below to test the property
            //modelInstance.puuid shouldBe ("TODO")
        }

        // to test the property `score`
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `shots`
        should("test shots") {
            // uncomment below to test the property
            //modelInstance.shots shouldBe ("TODO")
        }

        // to test the property `team`
        should("test team") {
            // uncomment below to test the property
            //modelInstance.team shouldBe ("TODO")
        }

        // to test the property `tier`
        should("test tier") {
            // uncomment below to test the property
            //modelInstance.tier shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `tag`
        should("test tag") {
            // uncomment below to test the property
            //modelInstance.tag shouldBe ("TODO")
        }

    }
}
