/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import henrikdevApiClient.models.StoreFeaturedV2Item

class StoreFeaturedV2ItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StoreFeaturedV2Item
        //val modelInstance = StoreFeaturedV2Item()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `basePrice`
        should("test basePrice") {
            // uncomment below to test the property
            //modelInstance.basePrice shouldBe ("TODO")
        }

        // to test the property `discountPercent`
        should("test discountPercent") {
            // uncomment below to test the property
            //modelInstance.discountPercent shouldBe ("TODO")
        }

        // to test the property `discountedPrice`
        should("test discountedPrice") {
            // uncomment below to test the property
            //modelInstance.discountedPrice shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `promoItem`
        should("test promoItem") {
            // uncomment below to test the property
            //modelInstance.promoItem shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

    }
}
