# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from henrikdev_api_client.models.agent_mastery_v1_reference import AgentMasteryV1Reference
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentMasteryV1Customization(BaseModel):
    """
    AgentMasteryV1Customization
    """ # noqa: E501
    background: Optional[AgentMasteryV1Reference] = None
    border: Optional[AgentMasteryV1Reference] = None
    clip: Optional[AgentMasteryV1Reference] = None
    hype: Optional[AgentMasteryV1Reference] = None
    __properties: ClassVar[List[str]] = ["background", "border", "clip", "hype"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentMasteryV1Customization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of background
        if self.background:
            _dict['background'] = self.background.to_dict()
        # override the default output from pydantic by calling `to_dict()` of border
        if self.border:
            _dict['border'] = self.border.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clip
        if self.clip:
            _dict['clip'] = self.clip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hype
        if self.hype:
            _dict['hype'] = self.hype.to_dict()
        # set to None if background (nullable) is None
        # and model_fields_set contains the field
        if self.background is None and "background" in self.model_fields_set:
            _dict['background'] = None

        # set to None if border (nullable) is None
        # and model_fields_set contains the field
        if self.border is None and "border" in self.model_fields_set:
            _dict['border'] = None

        # set to None if clip (nullable) is None
        # and model_fields_set contains the field
        if self.clip is None and "clip" in self.model_fields_set:
            _dict['clip'] = None

        # set to None if hype (nullable) is None
        # and model_fields_set contains the field
        if self.hype is None and "hype" in self.model_fields_set:
            _dict['hype'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentMasteryV1Customization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "background": AgentMasteryV1Reference.from_dict(obj["background"]) if obj.get("background") is not None else None,
            "border": AgentMasteryV1Reference.from_dict(obj["border"]) if obj.get("border") is not None else None,
            "clip": AgentMasteryV1Reference.from_dict(obj["clip"]) if obj.get("clip") is not None else None,
            "hype": AgentMasteryV1Reference.from_dict(obj["hype"]) if obj.get("hype") is not None else None
        })
        return _obj


