# coding: utf-8

"""
    HenrikDev API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebsiteV1Data(BaseModel):
    """
    WebsiteV1Data
    """ # noqa: E501
    banner_url: Optional[StrictStr] = None
    category: StrictStr
    var_date: StrictStr = Field(alias="date")
    description: Optional[StrictStr] = None
    external_link: Optional[StrictStr] = None
    id: StrictStr
    title: StrictStr
    url: StrictStr
    __properties: ClassVar[List[str]] = ["banner_url", "category", "date", "description", "external_link", "id", "title", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebsiteV1Data from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if banner_url (nullable) is None
        # and model_fields_set contains the field
        if self.banner_url is None and "banner_url" in self.model_fields_set:
            _dict['banner_url'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if external_link (nullable) is None
        # and model_fields_set contains the field
        if self.external_link is None and "external_link" in self.model_fields_set:
            _dict['external_link'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebsiteV1Data from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "banner_url": obj.get("banner_url"),
            "category": obj.get("category"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "external_link": obj.get("external_link"),
            "id": obj.get("id"),
            "title": obj.get("title"),
            "url": obj.get("url")
        })
        return _obj


