/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountV1DataCard {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "large")]
    pub large: String,
    #[serde(rename = "small")]
    pub small: String,
    #[serde(rename = "wide")]
    pub wide: String,
}

impl AccountV1DataCard {
    pub fn new(id: String, large: String, small: String, wide: String) -> AccountV1DataCard {
        AccountV1DataCard {
            id,
            large,
            small,
            wide,
        }
    }
}

