/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccoladesV1Response {
    #[serde(rename = "data")]
    pub data: Box<models::AccoladesV1Data>,
    #[serde(rename = "status")]
    pub status: u32,
}

impl AccoladesV1Response {
    pub fn new(data: models::AccoladesV1Data, status: u32) -> AccoladesV1Response {
        AccoladesV1Response {
            data: Box::new(data),
            status,
        }
    }
}

