/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentMasteryV1DetailResponse {
    #[serde(rename = "data")]
    pub data: Box<models::AgentMasteryV1DetailData>,
    #[serde(rename = "status")]
    pub status: u32,
}

impl AgentMasteryV1DetailResponse {
    pub fn new(data: models::AgentMasteryV1DetailData, status: u32) -> AgentMasteryV1DetailResponse {
        AgentMasteryV1DetailResponse {
            data: Box::new(data),
            status,
        }
    }
}

