/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2MatchTeam {
    #[serde(rename = "is_winner")]
    pub is_winner: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score: Option<Option<u32>>,
}

impl EsportsV2MatchTeam {
    pub fn new(is_winner: bool, name: String) -> EsportsV2MatchTeam {
        EsportsV2MatchTeam {
            is_winner,
            name,
            score: None,
        }
    }
}

