/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV1DataMatchTeamsRecord {
    #[serde(rename = "losses")]
    pub losses: i32,
    #[serde(rename = "wins")]
    pub wins: i32,
}

impl EsportsV1DataMatchTeamsRecord {
    pub fn new(losses: i32, wins: i32) -> EsportsV1DataMatchTeamsRecord {
        EsportsV1DataMatchTeamsRecord {
            losses,
            wins,
        }
    }
}

