/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2Event {
    #[serde(rename = "dates")]
    pub dates: Box<models::EsportsV2Date>,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "status")]
    pub status: models::EsportsV2EventStatus,
    #[serde(rename = "title")]
    pub title: String,
}

impl EsportsV2Event {
    pub fn new(dates: models::EsportsV2Date, icon: String, id: u32, price: String, region: String, slug: String, status: models::EsportsV2EventStatus, title: String) -> EsportsV2Event {
        EsportsV2Event {
            dates: Box::new(dates),
            icon,
            id,
            price,
            region,
            slug,
            status,
            title,
        }
    }
}

