/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2Social {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl EsportsV2Social {
    pub fn new(platform: String, url: String) -> EsportsV2Social {
        EsportsV2Social {
            platform,
            url,
        }
    }
}

