/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2MatchEvent {
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "series")]
    pub series: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl EsportsV2MatchEvent {
    pub fn new(icon: String, id: u32, series: String, slug: String, title: String) -> EsportsV2MatchEvent {
        EsportsV2MatchEvent {
            icon,
            id,
            series,
            slug,
            title,
        }
    }
}

