/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2MatchGameTeam {
    #[serde(rename = "is_winner")]
    pub is_winner: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "players")]
    pub players: Vec<models::EsportsV2MatchGamePlayer>,
    #[serde(rename = "score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score: Option<Option<u32>>,
    #[serde(rename = "score_ct", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score_ct: Option<Option<u32>>,
    #[serde(rename = "score_t", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score_t: Option<Option<u32>>,
}

impl EsportsV2MatchGameTeam {
    pub fn new(is_winner: bool, name: String, players: Vec<models::EsportsV2MatchGamePlayer>) -> EsportsV2MatchGameTeam {
        EsportsV2MatchGameTeam {
            is_winner,
            name,
            players,
            score: None,
            score_ct: None,
            score_t: None,
        }
    }
}

