/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV2MatchPlayer {
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nation")]
    pub nation: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl EsportsV2MatchPlayer {
    pub fn new(id: u32, name: String, nation: String, slug: String) -> EsportsV2MatchPlayer {
        EsportsV2MatchPlayer {
            id,
            name,
            nation,
            slug,
        }
    }
}

