/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsportsV1DataMatchTeams {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "game_wins")]
    pub game_wins: i32,
    #[serde(rename = "has_won")]
    pub has_won: bool,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "record")]
    pub record: Box<models::EsportsV1DataMatchTeamsRecord>,
}

impl EsportsV1DataMatchTeams {
    pub fn new(code: String, game_wins: i32, has_won: bool, icon: String, name: String, record: models::EsportsV1DataMatchTeamsRecord) -> EsportsV1DataMatchTeams {
        EsportsV1DataMatchTeams {
            code,
            game_wins,
            has_won,
            icon,
            name,
            record: Box::new(record),
        }
    }
}

