/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV2Response {
    #[serde(rename = "data")]
    pub data: Box<models::MatchesV2Data>,
    #[serde(rename = "status")]
    pub status: u32,
}

impl MatchesV2Response {
    pub fn new(data: models::MatchesV2Data, status: u32) -> MatchesV2Response {
        MatchesV2Response {
            data: Box::new(data),
            status,
        }
    }
}

