/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV4DataPlayerStatsDamage {
    #[serde(rename = "dealt")]
    pub dealt: i32,
    #[serde(rename = "received")]
    pub received: i32,
}

impl MatchesV4DataPlayerStatsDamage {
    pub fn new(dealt: i32, received: i32) -> MatchesV4DataPlayerStatsDamage {
        MatchesV4DataPlayerStatsDamage {
            dealt,
            received,
        }
    }
}

