/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV4DataTeamHealth {
    #[serde(rename = "remaining")]
    pub remaining: u32,
    #[serde(rename = "starting")]
    pub starting: u32,
}

impl MatchesV4DataTeamHealth {
    pub fn new(remaining: u32, starting: u32) -> MatchesV4DataTeamHealth {
        MatchesV4DataTeamHealth {
            remaining,
            starting,
        }
    }
}

