/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV4DataCoach {
    #[serde(rename = "puuid")]
    pub puuid: String,
    #[serde(rename = "team_id")]
    pub team_id: String,
}

impl MatchesV4DataCoach {
    pub fn new(puuid: String, team_id: String) -> MatchesV4DataCoach {
        MatchesV4DataCoach {
            puuid,
            team_id,
        }
    }
}

