/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV2DataPlayerAssetsCard {
    #[serde(rename = "large")]
    pub large: String,
    #[serde(rename = "small")]
    pub small: String,
    #[serde(rename = "wide")]
    pub wide: String,
}

impl MatchesV2DataPlayerAssetsCard {
    pub fn new(large: String, small: String, wide: String) -> MatchesV2DataPlayerAssetsCard {
        MatchesV2DataPlayerAssetsCard {
            large,
            small,
            wide,
        }
    }
}

