/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV2DataTeamRoster {
    #[serde(rename = "customization")]
    pub customization: Box<models::MatchesV2DataTeamRosterCustomization>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "members")]
    pub members: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tag")]
    pub tag: String,
}

impl MatchesV2DataTeamRoster {
    pub fn new(customization: models::MatchesV2DataTeamRosterCustomization, id: String, members: Vec<String>, name: String, tag: String) -> MatchesV2DataTeamRoster {
        MatchesV2DataTeamRoster {
            customization: Box::new(customization),
            id,
            members,
            name,
            tag,
        }
    }
}

