/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV4DataRoundPlayerStatsEconomyArmor {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl MatchesV4DataRoundPlayerStatsEconomyArmor {
    pub fn new(id: String) -> MatchesV4DataRoundPlayerStatsEconomyArmor {
        MatchesV4DataRoundPlayerStatsEconomyArmor {
            id,
            name: None,
        }
    }
}

