/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatchesV4DataPlayerPerformanceUtilityRatings : Known trends: double_down, down, neutral, up, double_up. Unknown upstream trends are preserved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesV4DataPlayerPerformanceUtilityRatings {
    #[serde(rename = "assists")]
    pub assists: String,
    #[serde(rename = "defuses")]
    pub defuses: String,
    #[serde(rename = "plants")]
    pub plants: String,
    #[serde(rename = "utility_usage")]
    pub utility_usage: String,
}

impl MatchesV4DataPlayerPerformanceUtilityRatings {
    /// Known trends: double_down, down, neutral, up, double_up. Unknown upstream trends are preserved.
    pub fn new(assists: String, defuses: String, plants: String, utility_usage: String) -> MatchesV4DataPlayerPerformanceUtilityRatings {
        MatchesV4DataPlayerPerformanceUtilityRatings {
            assists,
            defuses,
            plants,
            utility_usage,
        }
    }
}

