/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MmrDataImages {
    #[serde(rename = "large")]
    pub large: String,
    #[serde(rename = "small")]
    pub small: String,
    #[serde(rename = "triangle_down")]
    pub triangle_down: String,
    #[serde(rename = "triangle_up")]
    pub triangle_up: String,
}

impl MmrDataImages {
    pub fn new(large: String, small: String, triangle_down: String, triangle_up: String) -> MmrDataImages {
        MmrDataImages {
            large,
            small,
            triangle_down,
            triangle_up,
        }
    }
}

