/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoredMatchTeam {
    #[serde(rename = "blue")]
    pub blue: u32,
    #[serde(rename = "red")]
    pub red: u32,
}

impl StoredMatchTeam {
    pub fn new(blue: u32, red: u32) -> StoredMatchTeam {
        StoredMatchTeam {
            blue,
            red,
        }
    }
}

