/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreFeaturedV1 {
    #[serde(rename = "FeaturedBundle")]
    pub featured_bundle: Box<models::FeaturedBundle>,
}

impl StoreFeaturedV1 {
    pub fn new(featured_bundle: models::FeaturedBundle) -> StoreFeaturedV1 {
        StoreFeaturedV1 {
            featured_bundle: Box::new(featured_bundle),
        }
    }
}

