/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreFeaturedV2Response {
    #[serde(rename = "data")]
    pub data: Vec<models::StoreFeaturedV2>,
    #[serde(rename = "status")]
    pub status: u32,
}

impl StoreFeaturedV2Response {
    pub fn new(data: Vec<models::StoreFeaturedV2>, status: u32) -> StoreFeaturedV2Response {
        StoreFeaturedV2Response {
            data,
            status,
        }
    }
}

