/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreFeaturedV2 {
    #[serde(rename = "bundle_price")]
    pub bundle_price: u32,
    #[serde(rename = "bundle_uuid")]
    pub bundle_uuid: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "items")]
    pub items: Vec<models::StoreFeaturedV2Item>,
    #[serde(rename = "seconds_remaining")]
    pub seconds_remaining: u32,
    #[serde(rename = "whole_sale_only")]
    pub whole_sale_only: bool,
}

impl StoreFeaturedV2 {
    pub fn new(bundle_price: u32, bundle_uuid: String, expires_at: String, items: Vec<models::StoreFeaturedV2Item>, seconds_remaining: u32, whole_sale_only: bool) -> StoreFeaturedV2 {
        StoreFeaturedV2 {
            bundle_price,
            bundle_uuid,
            expires_at,
            items,
            seconds_remaining,
            whole_sale_only,
        }
    }
}

