/*
 * HenrikDev API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValorantStoreFeaturedResponse : The v1 path returns the raw featured bundle envelope; the v2 path returns the parsed bundle list envelope.
/// The v1 path returns the raw featured bundle envelope; the v2 path returns the parsed bundle list envelope.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ValorantStoreFeaturedResponse {
    StoreFeaturedV1Response(Box<models::StoreFeaturedV1Response>),
    StoreFeaturedV2Response(Box<models::StoreFeaturedV2Response>),
}

impl Default for ValorantStoreFeaturedResponse {
    fn default() -> Self {
        Self::StoreFeaturedV1Response(Default::default())
    }
}

