/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoreOffersV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreOffersV1Response{}

// StoreOffersV1Response struct for StoreOffersV1Response
type StoreOffersV1Response struct {
	Data StoreOffersV1 `json:"data"`
	Status int32 `json:"status"`
}

type _StoreOffersV1Response StoreOffersV1Response

// NewStoreOffersV1Response instantiates a new StoreOffersV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreOffersV1Response(data StoreOffersV1, status int32) *StoreOffersV1Response {
	this := StoreOffersV1Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewStoreOffersV1ResponseWithDefaults instantiates a new StoreOffersV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreOffersV1ResponseWithDefaults() *StoreOffersV1Response {
	this := StoreOffersV1Response{}
	return &this
}

// GetData returns the Data field value
func (o *StoreOffersV1Response) GetData() StoreOffersV1 {
	if o == nil {
		var ret StoreOffersV1
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *StoreOffersV1Response) GetDataOk() (*StoreOffersV1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *StoreOffersV1Response) SetData(v StoreOffersV1) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *StoreOffersV1Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StoreOffersV1Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StoreOffersV1Response) SetStatus(v int32) {
	o.Status = v
}

func (o StoreOffersV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreOffersV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *StoreOffersV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreOffersV1Response := _StoreOffersV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreOffersV1Response)

	if err != nil {
		return err
	}

	*o = StoreOffersV1Response(varStoreOffersV1Response)

	return err
}

type NullableStoreOffersV1Response struct {
	value *StoreOffersV1Response
	isSet bool
}

func (v NullableStoreOffersV1Response) Get() *StoreOffersV1Response {
	return v.value
}

func (v *NullableStoreOffersV1Response) Set(val *StoreOffersV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreOffersV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreOffersV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreOffersV1Response(val *StoreOffersV1Response) *NullableStoreOffersV1Response {
	return &NullableStoreOffersV1Response{value: val, isSet: true}
}

func (v NullableStoreOffersV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreOffersV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


