/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV2HeadToHeadMatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV2HeadToHeadMatch{}

// EsportsV2HeadToHeadMatch struct for EsportsV2HeadToHeadMatch
type EsportsV2HeadToHeadMatch struct {
	Date string `json:"date"`
	Event EsportsV2HeadToHeadEvent `json:"event"`
	Match EsportsV2IdSlug `json:"match"`
	Score EsportsV2HeadToHeadScore `json:"score"`
}

type _EsportsV2HeadToHeadMatch EsportsV2HeadToHeadMatch

// NewEsportsV2HeadToHeadMatch instantiates a new EsportsV2HeadToHeadMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV2HeadToHeadMatch(date string, event EsportsV2HeadToHeadEvent, match EsportsV2IdSlug, score EsportsV2HeadToHeadScore) *EsportsV2HeadToHeadMatch {
	this := EsportsV2HeadToHeadMatch{}
	this.Date = date
	this.Event = event
	this.Match = match
	this.Score = score
	return &this
}

// NewEsportsV2HeadToHeadMatchWithDefaults instantiates a new EsportsV2HeadToHeadMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV2HeadToHeadMatchWithDefaults() *EsportsV2HeadToHeadMatch {
	this := EsportsV2HeadToHeadMatch{}
	return &this
}

// GetDate returns the Date field value
func (o *EsportsV2HeadToHeadMatch) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *EsportsV2HeadToHeadMatch) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *EsportsV2HeadToHeadMatch) SetDate(v string) {
	o.Date = v
}

// GetEvent returns the Event field value
func (o *EsportsV2HeadToHeadMatch) GetEvent() EsportsV2HeadToHeadEvent {
	if o == nil {
		var ret EsportsV2HeadToHeadEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EsportsV2HeadToHeadMatch) GetEventOk() (*EsportsV2HeadToHeadEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EsportsV2HeadToHeadMatch) SetEvent(v EsportsV2HeadToHeadEvent) {
	o.Event = v
}

// GetMatch returns the Match field value
func (o *EsportsV2HeadToHeadMatch) GetMatch() EsportsV2IdSlug {
	if o == nil {
		var ret EsportsV2IdSlug
		return ret
	}

	return o.Match
}

// GetMatchOk returns a tuple with the Match field value
// and a boolean to check if the value has been set.
func (o *EsportsV2HeadToHeadMatch) GetMatchOk() (*EsportsV2IdSlug, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Match, true
}

// SetMatch sets field value
func (o *EsportsV2HeadToHeadMatch) SetMatch(v EsportsV2IdSlug) {
	o.Match = v
}

// GetScore returns the Score field value
func (o *EsportsV2HeadToHeadMatch) GetScore() EsportsV2HeadToHeadScore {
	if o == nil {
		var ret EsportsV2HeadToHeadScore
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *EsportsV2HeadToHeadMatch) GetScoreOk() (*EsportsV2HeadToHeadScore, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *EsportsV2HeadToHeadMatch) SetScore(v EsportsV2HeadToHeadScore) {
	o.Score = v
}

func (o EsportsV2HeadToHeadMatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV2HeadToHeadMatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["event"] = o.Event
	toSerialize["match"] = o.Match
	toSerialize["score"] = o.Score
	return toSerialize, nil
}

func (o *EsportsV2HeadToHeadMatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"event",
		"match",
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV2HeadToHeadMatch := _EsportsV2HeadToHeadMatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV2HeadToHeadMatch)

	if err != nil {
		return err
	}

	*o = EsportsV2HeadToHeadMatch(varEsportsV2HeadToHeadMatch)

	return err
}

type NullableEsportsV2HeadToHeadMatch struct {
	value *EsportsV2HeadToHeadMatch
	isSet bool
}

func (v NullableEsportsV2HeadToHeadMatch) Get() *EsportsV2HeadToHeadMatch {
	return v.value
}

func (v *NullableEsportsV2HeadToHeadMatch) Set(val *EsportsV2HeadToHeadMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV2HeadToHeadMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV2HeadToHeadMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV2HeadToHeadMatch(val *EsportsV2HeadToHeadMatch) *NullableEsportsV2HeadToHeadMatch {
	return &NullableEsportsV2HeadToHeadMatch{value: val, isSet: true}
}

func (v NullableEsportsV2HeadToHeadMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV2HeadToHeadMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


