/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"fmt"
)

// AccoladeKind Known Goldstar IDs documented at https://valdocs.prometheuz.me/endpoint/goldstars. New IDs remain available via `GoldstarDefinition::id` even if not listed here.
type AccoladeKind string

// List of AccoladeKind
const (
	KILLS AccoladeKind = "kills"
	FIRST_BLOOD AccoladeKind = "first_blood"
	DAMAGE_PER_ROUND AccoladeKind = "damage_per_round"
	CLUTCHES AccoladeKind = "clutches"
	ACES AccoladeKind = "aces"
	TRADES AccoladeKind = "trades"
	HEADSHOT_PERCENTAGE AccoladeKind = "headshot_percentage"
	DISTINCTION AccoladeKind = "distinction"
	ASSISTS AccoladeKind = "assists"
	TOP_FRAG AccoladeKind = "top_frag"
	PLANTS AccoladeKind = "plants"
	MVP AccoladeKind = "mvp"
)

// All allowed values of AccoladeKind enum
var AllowedAccoladeKindEnumValues = []AccoladeKind{
	"kills",
	"first_blood",
	"damage_per_round",
	"clutches",
	"aces",
	"trades",
	"headshot_percentage",
	"distinction",
	"assists",
	"top_frag",
	"plants",
	"mvp",
}

func (v *AccoladeKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AccoladeKind(value)
	for _, existing := range AllowedAccoladeKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AccoladeKind", value)
}

// NewAccoladeKindFromValue returns a pointer to a valid AccoladeKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAccoladeKindFromValue(v string) (*AccoladeKind, error) {
	ev := AccoladeKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AccoladeKind: valid values are %v", v, AllowedAccoladeKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AccoladeKind) IsValid() bool {
	for _, existing := range AllowedAccoladeKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AccoladeKind value
func (v AccoladeKind) Ptr() *AccoladeKind {
	return &v
}

type NullableAccoladeKind struct {
	value *AccoladeKind
	isSet bool
}

func (v NullableAccoladeKind) Get() *AccoladeKind {
	return v.value
}

func (v *NullableAccoladeKind) Set(val *AccoladeKind) {
	v.value = val
	v.isSet = true
}

func (v NullableAccoladeKind) IsSet() bool {
	return v.isSet
}

func (v *NullableAccoladeKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccoladeKind(val *AccoladeKind) *NullableAccoladeKind {
	return &NullableAccoladeKind{value: val, isSet: true}
}

func (v NullableAccoladeKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccoladeKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

