/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebsiteByIdV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebsiteByIdV1Response{}

// WebsiteByIdV1Response struct for WebsiteByIdV1Response
type WebsiteByIdV1Response struct {
	Data WebsiteByIdV1Data `json:"data"`
	Status int32 `json:"status"`
}

type _WebsiteByIdV1Response WebsiteByIdV1Response

// NewWebsiteByIdV1Response instantiates a new WebsiteByIdV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebsiteByIdV1Response(data WebsiteByIdV1Data, status int32) *WebsiteByIdV1Response {
	this := WebsiteByIdV1Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewWebsiteByIdV1ResponseWithDefaults instantiates a new WebsiteByIdV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebsiteByIdV1ResponseWithDefaults() *WebsiteByIdV1Response {
	this := WebsiteByIdV1Response{}
	return &this
}

// GetData returns the Data field value
func (o *WebsiteByIdV1Response) GetData() WebsiteByIdV1Data {
	if o == nil {
		var ret WebsiteByIdV1Data
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebsiteByIdV1Response) GetDataOk() (*WebsiteByIdV1Data, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebsiteByIdV1Response) SetData(v WebsiteByIdV1Data) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *WebsiteByIdV1Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebsiteByIdV1Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebsiteByIdV1Response) SetStatus(v int32) {
	o.Status = v
}

func (o WebsiteByIdV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebsiteByIdV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *WebsiteByIdV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebsiteByIdV1Response := _WebsiteByIdV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebsiteByIdV1Response)

	if err != nil {
		return err
	}

	*o = WebsiteByIdV1Response(varWebsiteByIdV1Response)

	return err
}

type NullableWebsiteByIdV1Response struct {
	value *WebsiteByIdV1Response
	isSet bool
}

func (v NullableWebsiteByIdV1Response) Get() *WebsiteByIdV1Response {
	return v.value
}

func (v *NullableWebsiteByIdV1Response) Set(val *WebsiteByIdV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWebsiteByIdV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWebsiteByIdV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebsiteByIdV1Response(val *WebsiteByIdV1Response) *NullableWebsiteByIdV1Response {
	return &NullableWebsiteByIdV1Response{value: val, isSet: true}
}

func (v NullableWebsiteByIdV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebsiteByIdV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


