/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BsonObjectIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BsonObjectIdResponse{}

// BsonObjectIdResponse struct for BsonObjectIdResponse
type BsonObjectIdResponse struct {
	Oid string `json:"$oid" validate:"regexp=^[0-9a-f]{24}$"`
}

type _BsonObjectIdResponse BsonObjectIdResponse

// NewBsonObjectIdResponse instantiates a new BsonObjectIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBsonObjectIdResponse(oid string) *BsonObjectIdResponse {
	this := BsonObjectIdResponse{}
	this.Oid = oid
	return &this
}

// NewBsonObjectIdResponseWithDefaults instantiates a new BsonObjectIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBsonObjectIdResponseWithDefaults() *BsonObjectIdResponse {
	this := BsonObjectIdResponse{}
	return &this
}

// GetOid returns the Oid field value
func (o *BsonObjectIdResponse) GetOid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Oid
}

// GetOidOk returns a tuple with the Oid field value
// and a boolean to check if the value has been set.
func (o *BsonObjectIdResponse) GetOidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oid, true
}

// SetOid sets field value
func (o *BsonObjectIdResponse) SetOid(v string) {
	o.Oid = v
}

func (o BsonObjectIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BsonObjectIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["$oid"] = o.Oid
	return toSerialize, nil
}

func (o *BsonObjectIdResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"$oid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBsonObjectIdResponse := _BsonObjectIdResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBsonObjectIdResponse)

	if err != nil {
		return err
	}

	*o = BsonObjectIdResponse(varBsonObjectIdResponse)

	return err
}

type NullableBsonObjectIdResponse struct {
	value *BsonObjectIdResponse
	isSet bool
}

func (v NullableBsonObjectIdResponse) Get() *BsonObjectIdResponse {
	return v.value
}

func (v *NullableBsonObjectIdResponse) Set(val *BsonObjectIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBsonObjectIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBsonObjectIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBsonObjectIdResponse(val *BsonObjectIdResponse) *NullableBsonObjectIdResponse {
	return &NullableBsonObjectIdResponse{value: val, isSet: true}
}

func (v NullableBsonObjectIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBsonObjectIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


