/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchesV4HistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchesV4HistoryResponse{}

// MatchesV4HistoryResponse struct for MatchesV4HistoryResponse
type MatchesV4HistoryResponse struct {
	Data []MatchesV4Data `json:"data"`
	Status int32 `json:"status"`
}

type _MatchesV4HistoryResponse MatchesV4HistoryResponse

// NewMatchesV4HistoryResponse instantiates a new MatchesV4HistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchesV4HistoryResponse(data []MatchesV4Data, status int32) *MatchesV4HistoryResponse {
	this := MatchesV4HistoryResponse{}
	this.Data = data
	this.Status = status
	return &this
}

// NewMatchesV4HistoryResponseWithDefaults instantiates a new MatchesV4HistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchesV4HistoryResponseWithDefaults() *MatchesV4HistoryResponse {
	this := MatchesV4HistoryResponse{}
	return &this
}

// GetData returns the Data field value
func (o *MatchesV4HistoryResponse) GetData() []MatchesV4Data {
	if o == nil {
		var ret []MatchesV4Data
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MatchesV4HistoryResponse) GetDataOk() ([]MatchesV4Data, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MatchesV4HistoryResponse) SetData(v []MatchesV4Data) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *MatchesV4HistoryResponse) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MatchesV4HistoryResponse) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MatchesV4HistoryResponse) SetStatus(v int32) {
	o.Status = v
}

func (o MatchesV4HistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchesV4HistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *MatchesV4HistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchesV4HistoryResponse := _MatchesV4HistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchesV4HistoryResponse)

	if err != nil {
		return err
	}

	*o = MatchesV4HistoryResponse(varMatchesV4HistoryResponse)

	return err
}

type NullableMatchesV4HistoryResponse struct {
	value *MatchesV4HistoryResponse
	isSet bool
}

func (v NullableMatchesV4HistoryResponse) Get() *MatchesV4HistoryResponse {
	return v.value
}

func (v *NullableMatchesV4HistoryResponse) Set(val *MatchesV4HistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesV4HistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesV4HistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesV4HistoryResponse(val *MatchesV4HistoryResponse) *NullableMatchesV4HistoryResponse {
	return &NullableMatchesV4HistoryResponse{value: val, isSet: true}
}

func (v NullableMatchesV4HistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesV4HistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


