/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RawV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawV1Response{}

// RawV1Response struct for RawV1Response
type RawV1Response struct {
	Data NullableRawV1ResponseData `json:"data"`
	Status int32 `json:"status"`
}

type _RawV1Response RawV1Response

// NewRawV1Response instantiates a new RawV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawV1Response(data NullableRawV1ResponseData, status int32) *RawV1Response {
	this := RawV1Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewRawV1ResponseWithDefaults instantiates a new RawV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawV1ResponseWithDefaults() *RawV1Response {
	this := RawV1Response{}
	return &this
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for RawV1ResponseData will be returned
func (o *RawV1Response) GetData() RawV1ResponseData {
	if o == nil || o.Data.Get() == nil {
		var ret RawV1ResponseData
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RawV1Response) GetDataOk() (*RawV1ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *RawV1Response) SetData(v RawV1ResponseData) {
	o.Data.Set(&v)
}

// GetStatus returns the Status field value
func (o *RawV1Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RawV1Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RawV1Response) SetStatus(v int32) {
	o.Status = v
}

func (o RawV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data.Get()
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *RawV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRawV1Response := _RawV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRawV1Response)

	if err != nil {
		return err
	}

	*o = RawV1Response(varRawV1Response)

	return err
}

type NullableRawV1Response struct {
	value *RawV1Response
	isSet bool
}

func (v NullableRawV1Response) Get() *RawV1Response {
	return v.value
}

func (v *NullableRawV1Response) Set(val *RawV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRawV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRawV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawV1Response(val *RawV1Response) *NullableRawV1Response {
	return &NullableRawV1Response{value: val, isSet: true}
}

func (v NullableRawV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


