/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccoladesV1SeasonId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccoladesV1SeasonId{}

// AccoladesV1SeasonId struct for AccoladesV1SeasonId
type AccoladesV1SeasonId struct {
	Id string `json:"id"`
	Short NullableString `json:"short,omitempty"`
}

type _AccoladesV1SeasonId AccoladesV1SeasonId

// NewAccoladesV1SeasonId instantiates a new AccoladesV1SeasonId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccoladesV1SeasonId(id string) *AccoladesV1SeasonId {
	this := AccoladesV1SeasonId{}
	this.Id = id
	return &this
}

// NewAccoladesV1SeasonIdWithDefaults instantiates a new AccoladesV1SeasonId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccoladesV1SeasonIdWithDefaults() *AccoladesV1SeasonId {
	this := AccoladesV1SeasonId{}
	return &this
}

// GetId returns the Id field value
func (o *AccoladesV1SeasonId) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccoladesV1SeasonId) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccoladesV1SeasonId) SetId(v string) {
	o.Id = v
}

// GetShort returns the Short field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccoladesV1SeasonId) GetShort() string {
	if o == nil || IsNil(o.Short.Get()) {
		var ret string
		return ret
	}
	return *o.Short.Get()
}

// GetShortOk returns a tuple with the Short field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccoladesV1SeasonId) GetShortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Short.Get(), o.Short.IsSet()
}

// HasShort returns a boolean if a field has been set.
func (o *AccoladesV1SeasonId) HasShort() bool {
	if o != nil && o.Short.IsSet() {
		return true
	}

	return false
}

// SetShort gets a reference to the given NullableString and assigns it to the Short field.
func (o *AccoladesV1SeasonId) SetShort(v string) {
	o.Short.Set(&v)
}
// SetShortNil sets the value for Short to be an explicit nil
func (o *AccoladesV1SeasonId) SetShortNil() {
	o.Short.Set(nil)
}

// UnsetShort ensures that no value is present for Short, not even an explicit nil
func (o *AccoladesV1SeasonId) UnsetShort() {
	o.Short.Unset()
}

func (o AccoladesV1SeasonId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccoladesV1SeasonId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Short.IsSet() {
		toSerialize["short"] = o.Short.Get()
	}
	return toSerialize, nil
}

func (o *AccoladesV1SeasonId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccoladesV1SeasonId := _AccoladesV1SeasonId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccoladesV1SeasonId)

	if err != nil {
		return err
	}

	*o = AccoladesV1SeasonId(varAccoladesV1SeasonId)

	return err
}

type NullableAccoladesV1SeasonId struct {
	value *AccoladesV1SeasonId
	isSet bool
}

func (v NullableAccoladesV1SeasonId) Get() *AccoladesV1SeasonId {
	return v.value
}

func (v *NullableAccoladesV1SeasonId) Set(val *AccoladesV1SeasonId) {
	v.value = val
	v.isSet = true
}

func (v NullableAccoladesV1SeasonId) IsSet() bool {
	return v.isSet
}

func (v *NullableAccoladesV1SeasonId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccoladesV1SeasonId(val *AccoladesV1SeasonId) *NullableAccoladesV1SeasonId {
	return &NullableAccoladesV1SeasonId{value: val, isSet: true}
}

func (v NullableAccoladesV1SeasonId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccoladesV1SeasonId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


