/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentMasteryV1Module type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMasteryV1Module{}

// AgentMasteryV1Module struct for AgentMasteryV1Module
type AgentMasteryV1Module struct {
	Id NullableString `json:"id,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Stat AgentMasteryV1Reference `json:"stat"`
	Value float64 `json:"value"`
}

type _AgentMasteryV1Module AgentMasteryV1Module

// NewAgentMasteryV1Module instantiates a new AgentMasteryV1Module object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMasteryV1Module(stat AgentMasteryV1Reference, value float64) *AgentMasteryV1Module {
	this := AgentMasteryV1Module{}
	this.Stat = stat
	this.Value = value
	return &this
}

// NewAgentMasteryV1ModuleWithDefaults instantiates a new AgentMasteryV1Module object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMasteryV1ModuleWithDefaults() *AgentMasteryV1Module {
	this := AgentMasteryV1Module{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentMasteryV1Module) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentMasteryV1Module) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *AgentMasteryV1Module) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *AgentMasteryV1Module) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *AgentMasteryV1Module) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *AgentMasteryV1Module) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentMasteryV1Module) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentMasteryV1Module) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AgentMasteryV1Module) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AgentMasteryV1Module) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *AgentMasteryV1Module) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AgentMasteryV1Module) UnsetName() {
	o.Name.Unset()
}

// GetStat returns the Stat field value
func (o *AgentMasteryV1Module) GetStat() AgentMasteryV1Reference {
	if o == nil {
		var ret AgentMasteryV1Reference
		return ret
	}

	return o.Stat
}

// GetStatOk returns a tuple with the Stat field value
// and a boolean to check if the value has been set.
func (o *AgentMasteryV1Module) GetStatOk() (*AgentMasteryV1Reference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stat, true
}

// SetStat sets field value
func (o *AgentMasteryV1Module) SetStat(v AgentMasteryV1Reference) {
	o.Stat = v
}

// GetValue returns the Value field value
func (o *AgentMasteryV1Module) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AgentMasteryV1Module) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AgentMasteryV1Module) SetValue(v float64) {
	o.Value = v
}

func (o AgentMasteryV1Module) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMasteryV1Module) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["stat"] = o.Stat
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *AgentMasteryV1Module) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stat",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentMasteryV1Module := _AgentMasteryV1Module{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentMasteryV1Module)

	if err != nil {
		return err
	}

	*o = AgentMasteryV1Module(varAgentMasteryV1Module)

	return err
}

type NullableAgentMasteryV1Module struct {
	value *AgentMasteryV1Module
	isSet bool
}

func (v NullableAgentMasteryV1Module) Get() *AgentMasteryV1Module {
	return v.value
}

func (v *NullableAgentMasteryV1Module) Set(val *AgentMasteryV1Module) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMasteryV1Module) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMasteryV1Module) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMasteryV1Module(val *AgentMasteryV1Module) *NullableAgentMasteryV1Module {
	return &NullableAgentMasteryV1Module{value: val, isSet: true}
}

func (v NullableAgentMasteryV1Module) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMasteryV1Module) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


