/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV2PlayerPerformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV2PlayerPerformance{}

// EsportsV2PlayerPerformance struct for EsportsV2PlayerPerformance
type EsportsV2PlayerPerformance struct {
	Clutches EsportsV2PlayerPerformanceClutches `json:"clutches"`
	Defuses int32 `json:"defuses"`
	EconRating int32 `json:"econ_rating"`
	MultiKills EsportsV2PlayerPerformanceMultiKills `json:"multi_kills"`
	Plants int32 `json:"plants"`
	Player EsportsV2PlayerPerformancePlayer `json:"player"`
}

type _EsportsV2PlayerPerformance EsportsV2PlayerPerformance

// NewEsportsV2PlayerPerformance instantiates a new EsportsV2PlayerPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV2PlayerPerformance(clutches EsportsV2PlayerPerformanceClutches, defuses int32, econRating int32, multiKills EsportsV2PlayerPerformanceMultiKills, plants int32, player EsportsV2PlayerPerformancePlayer) *EsportsV2PlayerPerformance {
	this := EsportsV2PlayerPerformance{}
	this.Clutches = clutches
	this.Defuses = defuses
	this.EconRating = econRating
	this.MultiKills = multiKills
	this.Plants = plants
	this.Player = player
	return &this
}

// NewEsportsV2PlayerPerformanceWithDefaults instantiates a new EsportsV2PlayerPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV2PlayerPerformanceWithDefaults() *EsportsV2PlayerPerformance {
	this := EsportsV2PlayerPerformance{}
	return &this
}

// GetClutches returns the Clutches field value
func (o *EsportsV2PlayerPerformance) GetClutches() EsportsV2PlayerPerformanceClutches {
	if o == nil {
		var ret EsportsV2PlayerPerformanceClutches
		return ret
	}

	return o.Clutches
}

// GetClutchesOk returns a tuple with the Clutches field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetClutchesOk() (*EsportsV2PlayerPerformanceClutches, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Clutches, true
}

// SetClutches sets field value
func (o *EsportsV2PlayerPerformance) SetClutches(v EsportsV2PlayerPerformanceClutches) {
	o.Clutches = v
}

// GetDefuses returns the Defuses field value
func (o *EsportsV2PlayerPerformance) GetDefuses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Defuses
}

// GetDefusesOk returns a tuple with the Defuses field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetDefusesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Defuses, true
}

// SetDefuses sets field value
func (o *EsportsV2PlayerPerformance) SetDefuses(v int32) {
	o.Defuses = v
}

// GetEconRating returns the EconRating field value
func (o *EsportsV2PlayerPerformance) GetEconRating() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EconRating
}

// GetEconRatingOk returns a tuple with the EconRating field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetEconRatingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EconRating, true
}

// SetEconRating sets field value
func (o *EsportsV2PlayerPerformance) SetEconRating(v int32) {
	o.EconRating = v
}

// GetMultiKills returns the MultiKills field value
func (o *EsportsV2PlayerPerformance) GetMultiKills() EsportsV2PlayerPerformanceMultiKills {
	if o == nil {
		var ret EsportsV2PlayerPerformanceMultiKills
		return ret
	}

	return o.MultiKills
}

// GetMultiKillsOk returns a tuple with the MultiKills field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetMultiKillsOk() (*EsportsV2PlayerPerformanceMultiKills, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MultiKills, true
}

// SetMultiKills sets field value
func (o *EsportsV2PlayerPerformance) SetMultiKills(v EsportsV2PlayerPerformanceMultiKills) {
	o.MultiKills = v
}

// GetPlants returns the Plants field value
func (o *EsportsV2PlayerPerformance) GetPlants() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plants
}

// GetPlantsOk returns a tuple with the Plants field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetPlantsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plants, true
}

// SetPlants sets field value
func (o *EsportsV2PlayerPerformance) SetPlants(v int32) {
	o.Plants = v
}

// GetPlayer returns the Player field value
func (o *EsportsV2PlayerPerformance) GetPlayer() EsportsV2PlayerPerformancePlayer {
	if o == nil {
		var ret EsportsV2PlayerPerformancePlayer
		return ret
	}

	return o.Player
}

// GetPlayerOk returns a tuple with the Player field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlayerPerformance) GetPlayerOk() (*EsportsV2PlayerPerformancePlayer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Player, true
}

// SetPlayer sets field value
func (o *EsportsV2PlayerPerformance) SetPlayer(v EsportsV2PlayerPerformancePlayer) {
	o.Player = v
}

func (o EsportsV2PlayerPerformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV2PlayerPerformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clutches"] = o.Clutches
	toSerialize["defuses"] = o.Defuses
	toSerialize["econ_rating"] = o.EconRating
	toSerialize["multi_kills"] = o.MultiKills
	toSerialize["plants"] = o.Plants
	toSerialize["player"] = o.Player
	return toSerialize, nil
}

func (o *EsportsV2PlayerPerformance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clutches",
		"defuses",
		"econ_rating",
		"multi_kills",
		"plants",
		"player",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV2PlayerPerformance := _EsportsV2PlayerPerformance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV2PlayerPerformance)

	if err != nil {
		return err
	}

	*o = EsportsV2PlayerPerformance(varEsportsV2PlayerPerformance)

	return err
}

type NullableEsportsV2PlayerPerformance struct {
	value *EsportsV2PlayerPerformance
	isSet bool
}

func (v NullableEsportsV2PlayerPerformance) Get() *EsportsV2PlayerPerformance {
	return v.value
}

func (v *NullableEsportsV2PlayerPerformance) Set(val *EsportsV2PlayerPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV2PlayerPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV2PlayerPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV2PlayerPerformance(val *EsportsV2PlayerPerformance) *NullableEsportsV2PlayerPerformance {
	return &NullableEsportsV2PlayerPerformance{value: val, isSet: true}
}

func (v NullableEsportsV2PlayerPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV2PlayerPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


