/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"fmt"
)

// ValorantStoreVersion Store response version. Values are case-sensitive.
type ValorantStoreVersion string

// List of ValorantStoreVersion
const (
	V1 ValorantStoreVersion = "v1"
	V2 ValorantStoreVersion = "v2"
)

// All allowed values of ValorantStoreVersion enum
var AllowedValorantStoreVersionEnumValues = []ValorantStoreVersion{
	"v1",
	"v2",
}

func (v *ValorantStoreVersion) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ValorantStoreVersion(value)
	for _, existing := range AllowedValorantStoreVersionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ValorantStoreVersion", value)
}

// NewValorantStoreVersionFromValue returns a pointer to a valid ValorantStoreVersion
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewValorantStoreVersionFromValue(v string) (*ValorantStoreVersion, error) {
	ev := ValorantStoreVersion(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ValorantStoreVersion: valid values are %v", v, AllowedValorantStoreVersionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ValorantStoreVersion) IsValid() bool {
	for _, existing := range AllowedValorantStoreVersionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ValorantStoreVersion value
func (v ValorantStoreVersion) Ptr() *ValorantStoreVersion {
	return &v
}

type NullableValorantStoreVersion struct {
	value *ValorantStoreVersion
	isSet bool
}

func (v NullableValorantStoreVersion) Get() *ValorantStoreVersion {
	return v.value
}

func (v *NullableValorantStoreVersion) Set(val *ValorantStoreVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableValorantStoreVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableValorantStoreVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValorantStoreVersion(val *ValorantStoreVersion) *NullableValorantStoreVersion {
	return &NullableValorantStoreVersion{value: val, isSet: true}
}

func (v NullableValorantStoreVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValorantStoreVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

