/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV1DataTournament type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV1DataTournament{}

// EsportsV1DataTournament struct for EsportsV1DataTournament
type EsportsV1DataTournament struct {
	Name string `json:"name"`
	Season string `json:"season"`
}

type _EsportsV1DataTournament EsportsV1DataTournament

// NewEsportsV1DataTournament instantiates a new EsportsV1DataTournament object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV1DataTournament(name string, season string) *EsportsV1DataTournament {
	this := EsportsV1DataTournament{}
	this.Name = name
	this.Season = season
	return &this
}

// NewEsportsV1DataTournamentWithDefaults instantiates a new EsportsV1DataTournament object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV1DataTournamentWithDefaults() *EsportsV1DataTournament {
	this := EsportsV1DataTournament{}
	return &this
}

// GetName returns the Name field value
func (o *EsportsV1DataTournament) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EsportsV1DataTournament) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EsportsV1DataTournament) SetName(v string) {
	o.Name = v
}

// GetSeason returns the Season field value
func (o *EsportsV1DataTournament) GetSeason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Season
}

// GetSeasonOk returns a tuple with the Season field value
// and a boolean to check if the value has been set.
func (o *EsportsV1DataTournament) GetSeasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Season, true
}

// SetSeason sets field value
func (o *EsportsV1DataTournament) SetSeason(v string) {
	o.Season = v
}

func (o EsportsV1DataTournament) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV1DataTournament) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["season"] = o.Season
	return toSerialize, nil
}

func (o *EsportsV1DataTournament) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"season",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV1DataTournament := _EsportsV1DataTournament{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV1DataTournament)

	if err != nil {
		return err
	}

	*o = EsportsV1DataTournament(varEsportsV1DataTournament)

	return err
}

type NullableEsportsV1DataTournament struct {
	value *EsportsV1DataTournament
	isSet bool
}

func (v NullableEsportsV1DataTournament) Get() *EsportsV1DataTournament {
	return v.value
}

func (v *NullableEsportsV1DataTournament) Set(val *EsportsV1DataTournament) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV1DataTournament) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV1DataTournament) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV1DataTournament(val *EsportsV1DataTournament) *NullableEsportsV1DataTournament {
	return &NullableEsportsV1DataTournament{value: val, isSet: true}
}

func (v NullableEsportsV1DataTournament) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV1DataTournament) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


