/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MMRHistoryV2History type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MMRHistoryV2History{}

// MMRHistoryV2History struct for MMRHistoryV2History
type MMRHistoryV2History struct {
	Date string `json:"date"`
	Elo int32 `json:"elo"`
	LastChange int32 `json:"last_change"`
	Map MapIdNameCombo `json:"map"`
	MatchId string `json:"match_id"`
	RefundedRr int32 `json:"refunded_rr"`
	Rr int32 `json:"rr"`
	Season SeasonIdShortCombo `json:"season"`
	Tier TierIdNameCombo `json:"tier"`
	WasDerankProtected bool `json:"was_derank_protected"`
}

type _MMRHistoryV2History MMRHistoryV2History

// NewMMRHistoryV2History instantiates a new MMRHistoryV2History object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMMRHistoryV2History(date string, elo int32, lastChange int32, map_ MapIdNameCombo, matchId string, refundedRr int32, rr int32, season SeasonIdShortCombo, tier TierIdNameCombo, wasDerankProtected bool) *MMRHistoryV2History {
	this := MMRHistoryV2History{}
	this.Date = date
	this.Elo = elo
	this.LastChange = lastChange
	this.Map = map_
	this.MatchId = matchId
	this.RefundedRr = refundedRr
	this.Rr = rr
	this.Season = season
	this.Tier = tier
	this.WasDerankProtected = wasDerankProtected
	return &this
}

// NewMMRHistoryV2HistoryWithDefaults instantiates a new MMRHistoryV2History object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMMRHistoryV2HistoryWithDefaults() *MMRHistoryV2History {
	this := MMRHistoryV2History{}
	return &this
}

// GetDate returns the Date field value
func (o *MMRHistoryV2History) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *MMRHistoryV2History) SetDate(v string) {
	o.Date = v
}

// GetElo returns the Elo field value
func (o *MMRHistoryV2History) GetElo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Elo
}

// GetEloOk returns a tuple with the Elo field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetEloOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Elo, true
}

// SetElo sets field value
func (o *MMRHistoryV2History) SetElo(v int32) {
	o.Elo = v
}

// GetLastChange returns the LastChange field value
func (o *MMRHistoryV2History) GetLastChange() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastChange
}

// GetLastChangeOk returns a tuple with the LastChange field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetLastChangeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastChange, true
}

// SetLastChange sets field value
func (o *MMRHistoryV2History) SetLastChange(v int32) {
	o.LastChange = v
}

// GetMap returns the Map field value
func (o *MMRHistoryV2History) GetMap() MapIdNameCombo {
	if o == nil {
		var ret MapIdNameCombo
		return ret
	}

	return o.Map
}

// GetMapOk returns a tuple with the Map field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetMapOk() (*MapIdNameCombo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Map, true
}

// SetMap sets field value
func (o *MMRHistoryV2History) SetMap(v MapIdNameCombo) {
	o.Map = v
}

// GetMatchId returns the MatchId field value
func (o *MMRHistoryV2History) GetMatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetMatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatchId, true
}

// SetMatchId sets field value
func (o *MMRHistoryV2History) SetMatchId(v string) {
	o.MatchId = v
}

// GetRefundedRr returns the RefundedRr field value
func (o *MMRHistoryV2History) GetRefundedRr() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RefundedRr
}

// GetRefundedRrOk returns a tuple with the RefundedRr field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetRefundedRrOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefundedRr, true
}

// SetRefundedRr sets field value
func (o *MMRHistoryV2History) SetRefundedRr(v int32) {
	o.RefundedRr = v
}

// GetRr returns the Rr field value
func (o *MMRHistoryV2History) GetRr() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rr
}

// GetRrOk returns a tuple with the Rr field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetRrOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rr, true
}

// SetRr sets field value
func (o *MMRHistoryV2History) SetRr(v int32) {
	o.Rr = v
}

// GetSeason returns the Season field value
func (o *MMRHistoryV2History) GetSeason() SeasonIdShortCombo {
	if o == nil {
		var ret SeasonIdShortCombo
		return ret
	}

	return o.Season
}

// GetSeasonOk returns a tuple with the Season field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetSeasonOk() (*SeasonIdShortCombo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Season, true
}

// SetSeason sets field value
func (o *MMRHistoryV2History) SetSeason(v SeasonIdShortCombo) {
	o.Season = v
}

// GetTier returns the Tier field value
func (o *MMRHistoryV2History) GetTier() TierIdNameCombo {
	if o == nil {
		var ret TierIdNameCombo
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetTierOk() (*TierIdNameCombo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *MMRHistoryV2History) SetTier(v TierIdNameCombo) {
	o.Tier = v
}

// GetWasDerankProtected returns the WasDerankProtected field value
func (o *MMRHistoryV2History) GetWasDerankProtected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WasDerankProtected
}

// GetWasDerankProtectedOk returns a tuple with the WasDerankProtected field value
// and a boolean to check if the value has been set.
func (o *MMRHistoryV2History) GetWasDerankProtectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WasDerankProtected, true
}

// SetWasDerankProtected sets field value
func (o *MMRHistoryV2History) SetWasDerankProtected(v bool) {
	o.WasDerankProtected = v
}

func (o MMRHistoryV2History) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MMRHistoryV2History) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["elo"] = o.Elo
	toSerialize["last_change"] = o.LastChange
	toSerialize["map"] = o.Map
	toSerialize["match_id"] = o.MatchId
	toSerialize["refunded_rr"] = o.RefundedRr
	toSerialize["rr"] = o.Rr
	toSerialize["season"] = o.Season
	toSerialize["tier"] = o.Tier
	toSerialize["was_derank_protected"] = o.WasDerankProtected
	return toSerialize, nil
}

func (o *MMRHistoryV2History) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"elo",
		"last_change",
		"map",
		"match_id",
		"refunded_rr",
		"rr",
		"season",
		"tier",
		"was_derank_protected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMMRHistoryV2History := _MMRHistoryV2History{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMMRHistoryV2History)

	if err != nil {
		return err
	}

	*o = MMRHistoryV2History(varMMRHistoryV2History)

	return err
}

type NullableMMRHistoryV2History struct {
	value *MMRHistoryV2History
	isSet bool
}

func (v NullableMMRHistoryV2History) Get() *MMRHistoryV2History {
	return v.value
}

func (v *NullableMMRHistoryV2History) Set(val *MMRHistoryV2History) {
	v.value = val
	v.isSet = true
}

func (v NullableMMRHistoryV2History) IsSet() bool {
	return v.isSet
}

func (v *NullableMMRHistoryV2History) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMMRHistoryV2History(val *MMRHistoryV2History) *NullableMMRHistoryV2History {
	return &NullableMMRHistoryV2History{value: val, isSet: true}
}

func (v NullableMMRHistoryV2History) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMMRHistoryV2History) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


