/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV2MatchGameRound type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV2MatchGameRound{}

// EsportsV2MatchGameRound struct for EsportsV2MatchGameRound
type EsportsV2MatchGameRound struct {
	Round int32 `json:"round"`
	WinningSite string `json:"winning_site"`
	WinningTeam int32 `json:"winning_team"`
}

type _EsportsV2MatchGameRound EsportsV2MatchGameRound

// NewEsportsV2MatchGameRound instantiates a new EsportsV2MatchGameRound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV2MatchGameRound(round int32, winningSite string, winningTeam int32) *EsportsV2MatchGameRound {
	this := EsportsV2MatchGameRound{}
	this.Round = round
	this.WinningSite = winningSite
	this.WinningTeam = winningTeam
	return &this
}

// NewEsportsV2MatchGameRoundWithDefaults instantiates a new EsportsV2MatchGameRound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV2MatchGameRoundWithDefaults() *EsportsV2MatchGameRound {
	this := EsportsV2MatchGameRound{}
	return &this
}

// GetRound returns the Round field value
func (o *EsportsV2MatchGameRound) GetRound() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Round
}

// GetRoundOk returns a tuple with the Round field value
// and a boolean to check if the value has been set.
func (o *EsportsV2MatchGameRound) GetRoundOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Round, true
}

// SetRound sets field value
func (o *EsportsV2MatchGameRound) SetRound(v int32) {
	o.Round = v
}

// GetWinningSite returns the WinningSite field value
func (o *EsportsV2MatchGameRound) GetWinningSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WinningSite
}

// GetWinningSiteOk returns a tuple with the WinningSite field value
// and a boolean to check if the value has been set.
func (o *EsportsV2MatchGameRound) GetWinningSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WinningSite, true
}

// SetWinningSite sets field value
func (o *EsportsV2MatchGameRound) SetWinningSite(v string) {
	o.WinningSite = v
}

// GetWinningTeam returns the WinningTeam field value
func (o *EsportsV2MatchGameRound) GetWinningTeam() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WinningTeam
}

// GetWinningTeamOk returns a tuple with the WinningTeam field value
// and a boolean to check if the value has been set.
func (o *EsportsV2MatchGameRound) GetWinningTeamOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WinningTeam, true
}

// SetWinningTeam sets field value
func (o *EsportsV2MatchGameRound) SetWinningTeam(v int32) {
	o.WinningTeam = v
}

func (o EsportsV2MatchGameRound) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV2MatchGameRound) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["round"] = o.Round
	toSerialize["winning_site"] = o.WinningSite
	toSerialize["winning_team"] = o.WinningTeam
	return toSerialize, nil
}

func (o *EsportsV2MatchGameRound) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"round",
		"winning_site",
		"winning_team",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV2MatchGameRound := _EsportsV2MatchGameRound{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV2MatchGameRound)

	if err != nil {
		return err
	}

	*o = EsportsV2MatchGameRound(varEsportsV2MatchGameRound)

	return err
}

type NullableEsportsV2MatchGameRound struct {
	value *EsportsV2MatchGameRound
	isSet bool
}

func (v NullableEsportsV2MatchGameRound) Get() *EsportsV2MatchGameRound {
	return v.value
}

func (v *NullableEsportsV2MatchGameRound) Set(val *EsportsV2MatchGameRound) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV2MatchGameRound) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV2MatchGameRound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV2MatchGameRound(val *EsportsV2MatchGameRound) *NullableEsportsV2MatchGameRound {
	return &NullableEsportsV2MatchGameRound{value: val, isSet: true}
}

func (v NullableEsportsV2MatchGameRound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV2MatchGameRound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


