/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"fmt"
)

// ValorantWebsiteCategory Website category filter. Values are case-sensitive.
type ValorantWebsiteCategory string

// List of ValorantWebsiteCategory
const (
	GAME_UPDATES ValorantWebsiteCategory = "game_updates"
	DEV ValorantWebsiteCategory = "dev"
	ESPORTS ValorantWebsiteCategory = "esports"
	ANNOUNCEMENTS ValorantWebsiteCategory = "announcements"
	PATCH_NOTES ValorantWebsiteCategory = "patch_notes"
	COMMUNITY ValorantWebsiteCategory = "community"
)

// All allowed values of ValorantWebsiteCategory enum
var AllowedValorantWebsiteCategoryEnumValues = []ValorantWebsiteCategory{
	"game_updates",
	"dev",
	"esports",
	"announcements",
	"patch_notes",
	"community",
}

func (v *ValorantWebsiteCategory) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ValorantWebsiteCategory(value)
	for _, existing := range AllowedValorantWebsiteCategoryEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ValorantWebsiteCategory", value)
}

// NewValorantWebsiteCategoryFromValue returns a pointer to a valid ValorantWebsiteCategory
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewValorantWebsiteCategoryFromValue(v string) (*ValorantWebsiteCategory, error) {
	ev := ValorantWebsiteCategory(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ValorantWebsiteCategory: valid values are %v", v, AllowedValorantWebsiteCategoryEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ValorantWebsiteCategory) IsValid() bool {
	for _, existing := range AllowedValorantWebsiteCategoryEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ValorantWebsiteCategory value
func (v ValorantWebsiteCategory) Ptr() *ValorantWebsiteCategory {
	return &v
}

type NullableValorantWebsiteCategory struct {
	value *ValorantWebsiteCategory
	isSet bool
}

func (v NullableValorantWebsiteCategory) Get() *ValorantWebsiteCategory {
	return v.value
}

func (v *NullableValorantWebsiteCategory) Set(val *ValorantWebsiteCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableValorantWebsiteCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableValorantWebsiteCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValorantWebsiteCategory(val *ValorantWebsiteCategory) *NullableValorantWebsiteCategory {
	return &NullableValorantWebsiteCategory{value: val, isSet: true}
}

func (v NullableValorantWebsiteCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValorantWebsiteCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

