/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchesV2DataRoundPlayerStatsKillEventsAssistants type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchesV2DataRoundPlayerStatsKillEventsAssistants{}

// MatchesV2DataRoundPlayerStatsKillEventsAssistants struct for MatchesV2DataRoundPlayerStatsKillEventsAssistants
type MatchesV2DataRoundPlayerStatsKillEventsAssistants struct {
	AssistantDisplayName string `json:"assistant_display_name"`
	AssistantPuuid string `json:"assistant_puuid"`
	AssistantTeam string `json:"assistant_team"`
}

type _MatchesV2DataRoundPlayerStatsKillEventsAssistants MatchesV2DataRoundPlayerStatsKillEventsAssistants

// NewMatchesV2DataRoundPlayerStatsKillEventsAssistants instantiates a new MatchesV2DataRoundPlayerStatsKillEventsAssistants object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchesV2DataRoundPlayerStatsKillEventsAssistants(assistantDisplayName string, assistantPuuid string, assistantTeam string) *MatchesV2DataRoundPlayerStatsKillEventsAssistants {
	this := MatchesV2DataRoundPlayerStatsKillEventsAssistants{}
	this.AssistantDisplayName = assistantDisplayName
	this.AssistantPuuid = assistantPuuid
	this.AssistantTeam = assistantTeam
	return &this
}

// NewMatchesV2DataRoundPlayerStatsKillEventsAssistantsWithDefaults instantiates a new MatchesV2DataRoundPlayerStatsKillEventsAssistants object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchesV2DataRoundPlayerStatsKillEventsAssistantsWithDefaults() *MatchesV2DataRoundPlayerStatsKillEventsAssistants {
	this := MatchesV2DataRoundPlayerStatsKillEventsAssistants{}
	return &this
}

// GetAssistantDisplayName returns the AssistantDisplayName field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssistantDisplayName
}

// GetAssistantDisplayNameOk returns a tuple with the AssistantDisplayName field value
// and a boolean to check if the value has been set.
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssistantDisplayName, true
}

// SetAssistantDisplayName sets field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) SetAssistantDisplayName(v string) {
	o.AssistantDisplayName = v
}

// GetAssistantPuuid returns the AssistantPuuid field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantPuuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssistantPuuid
}

// GetAssistantPuuidOk returns a tuple with the AssistantPuuid field value
// and a boolean to check if the value has been set.
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantPuuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssistantPuuid, true
}

// SetAssistantPuuid sets field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) SetAssistantPuuid(v string) {
	o.AssistantPuuid = v
}

// GetAssistantTeam returns the AssistantTeam field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantTeam() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssistantTeam
}

// GetAssistantTeamOk returns a tuple with the AssistantTeam field value
// and a boolean to check if the value has been set.
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) GetAssistantTeamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssistantTeam, true
}

// SetAssistantTeam sets field value
func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) SetAssistantTeam(v string) {
	o.AssistantTeam = v
}

func (o MatchesV2DataRoundPlayerStatsKillEventsAssistants) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchesV2DataRoundPlayerStatsKillEventsAssistants) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assistant_display_name"] = o.AssistantDisplayName
	toSerialize["assistant_puuid"] = o.AssistantPuuid
	toSerialize["assistant_team"] = o.AssistantTeam
	return toSerialize, nil
}

func (o *MatchesV2DataRoundPlayerStatsKillEventsAssistants) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assistant_display_name",
		"assistant_puuid",
		"assistant_team",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchesV2DataRoundPlayerStatsKillEventsAssistants := _MatchesV2DataRoundPlayerStatsKillEventsAssistants{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchesV2DataRoundPlayerStatsKillEventsAssistants)

	if err != nil {
		return err
	}

	*o = MatchesV2DataRoundPlayerStatsKillEventsAssistants(varMatchesV2DataRoundPlayerStatsKillEventsAssistants)

	return err
}

type NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants struct {
	value *MatchesV2DataRoundPlayerStatsKillEventsAssistants
	isSet bool
}

func (v NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) Get() *MatchesV2DataRoundPlayerStatsKillEventsAssistants {
	return v.value
}

func (v *NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) Set(val *MatchesV2DataRoundPlayerStatsKillEventsAssistants) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesV2DataRoundPlayerStatsKillEventsAssistants(val *MatchesV2DataRoundPlayerStatsKillEventsAssistants) *NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants {
	return &NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants{value: val, isSet: true}
}

func (v NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesV2DataRoundPlayerStatsKillEventsAssistants) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


