/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV2PlacementEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV2PlacementEntry{}

// EsportsV2PlacementEntry struct for EsportsV2PlacementEntry
type EsportsV2PlacementEntry struct {
	Placement string `json:"placement"`
	Prize NullableString `json:"prize,omitempty"`
	Stage string `json:"stage"`
	Team NullableString `json:"team,omitempty"`
}

type _EsportsV2PlacementEntry EsportsV2PlacementEntry

// NewEsportsV2PlacementEntry instantiates a new EsportsV2PlacementEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV2PlacementEntry(placement string, stage string) *EsportsV2PlacementEntry {
	this := EsportsV2PlacementEntry{}
	this.Placement = placement
	this.Stage = stage
	return &this
}

// NewEsportsV2PlacementEntryWithDefaults instantiates a new EsportsV2PlacementEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV2PlacementEntryWithDefaults() *EsportsV2PlacementEntry {
	this := EsportsV2PlacementEntry{}
	return &this
}

// GetPlacement returns the Placement field value
func (o *EsportsV2PlacementEntry) GetPlacement() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Placement
}

// GetPlacementOk returns a tuple with the Placement field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlacementEntry) GetPlacementOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Placement, true
}

// SetPlacement sets field value
func (o *EsportsV2PlacementEntry) SetPlacement(v string) {
	o.Placement = v
}

// GetPrize returns the Prize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EsportsV2PlacementEntry) GetPrize() string {
	if o == nil || IsNil(o.Prize.Get()) {
		var ret string
		return ret
	}
	return *o.Prize.Get()
}

// GetPrizeOk returns a tuple with the Prize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EsportsV2PlacementEntry) GetPrizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prize.Get(), o.Prize.IsSet()
}

// HasPrize returns a boolean if a field has been set.
func (o *EsportsV2PlacementEntry) HasPrize() bool {
	if o != nil && o.Prize.IsSet() {
		return true
	}

	return false
}

// SetPrize gets a reference to the given NullableString and assigns it to the Prize field.
func (o *EsportsV2PlacementEntry) SetPrize(v string) {
	o.Prize.Set(&v)
}
// SetPrizeNil sets the value for Prize to be an explicit nil
func (o *EsportsV2PlacementEntry) SetPrizeNil() {
	o.Prize.Set(nil)
}

// UnsetPrize ensures that no value is present for Prize, not even an explicit nil
func (o *EsportsV2PlacementEntry) UnsetPrize() {
	o.Prize.Unset()
}

// GetStage returns the Stage field value
func (o *EsportsV2PlacementEntry) GetStage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stage
}

// GetStageOk returns a tuple with the Stage field value
// and a boolean to check if the value has been set.
func (o *EsportsV2PlacementEntry) GetStageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stage, true
}

// SetStage sets field value
func (o *EsportsV2PlacementEntry) SetStage(v string) {
	o.Stage = v
}

// GetTeam returns the Team field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EsportsV2PlacementEntry) GetTeam() string {
	if o == nil || IsNil(o.Team.Get()) {
		var ret string
		return ret
	}
	return *o.Team.Get()
}

// GetTeamOk returns a tuple with the Team field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EsportsV2PlacementEntry) GetTeamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Team.Get(), o.Team.IsSet()
}

// HasTeam returns a boolean if a field has been set.
func (o *EsportsV2PlacementEntry) HasTeam() bool {
	if o != nil && o.Team.IsSet() {
		return true
	}

	return false
}

// SetTeam gets a reference to the given NullableString and assigns it to the Team field.
func (o *EsportsV2PlacementEntry) SetTeam(v string) {
	o.Team.Set(&v)
}
// SetTeamNil sets the value for Team to be an explicit nil
func (o *EsportsV2PlacementEntry) SetTeamNil() {
	o.Team.Set(nil)
}

// UnsetTeam ensures that no value is present for Team, not even an explicit nil
func (o *EsportsV2PlacementEntry) UnsetTeam() {
	o.Team.Unset()
}

func (o EsportsV2PlacementEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV2PlacementEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["placement"] = o.Placement
	if o.Prize.IsSet() {
		toSerialize["prize"] = o.Prize.Get()
	}
	toSerialize["stage"] = o.Stage
	if o.Team.IsSet() {
		toSerialize["team"] = o.Team.Get()
	}
	return toSerialize, nil
}

func (o *EsportsV2PlacementEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"placement",
		"stage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV2PlacementEntry := _EsportsV2PlacementEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV2PlacementEntry)

	if err != nil {
		return err
	}

	*o = EsportsV2PlacementEntry(varEsportsV2PlacementEntry)

	return err
}

type NullableEsportsV2PlacementEntry struct {
	value *EsportsV2PlacementEntry
	isSet bool
}

func (v NullableEsportsV2PlacementEntry) Get() *EsportsV2PlacementEntry {
	return v.value
}

func (v *NullableEsportsV2PlacementEntry) Set(val *EsportsV2PlacementEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV2PlacementEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV2PlacementEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV2PlacementEntry(val *EsportsV2PlacementEntry) *NullableEsportsV2PlacementEntry {
	return &NullableEsportsV2PlacementEntry{value: val, isSet: true}
}

func (v NullableEsportsV2PlacementEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV2PlacementEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


