/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoredMatchMetaMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoredMatchMetaMap{}

// StoredMatchMetaMap struct for StoredMatchMetaMap
type StoredMatchMetaMap struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type _StoredMatchMetaMap StoredMatchMetaMap

// NewStoredMatchMetaMap instantiates a new StoredMatchMetaMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoredMatchMetaMap(id string, name string) *StoredMatchMetaMap {
	this := StoredMatchMetaMap{}
	this.Id = id
	this.Name = name
	return &this
}

// NewStoredMatchMetaMapWithDefaults instantiates a new StoredMatchMetaMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoredMatchMetaMapWithDefaults() *StoredMatchMetaMap {
	this := StoredMatchMetaMap{}
	return &this
}

// GetId returns the Id field value
func (o *StoredMatchMetaMap) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *StoredMatchMetaMap) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *StoredMatchMetaMap) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *StoredMatchMetaMap) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StoredMatchMetaMap) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StoredMatchMetaMap) SetName(v string) {
	o.Name = v
}

func (o StoredMatchMetaMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoredMatchMetaMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *StoredMatchMetaMap) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoredMatchMetaMap := _StoredMatchMetaMap{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoredMatchMetaMap)

	if err != nil {
		return err
	}

	*o = StoredMatchMetaMap(varStoredMatchMetaMap)

	return err
}

type NullableStoredMatchMetaMap struct {
	value *StoredMatchMetaMap
	isSet bool
}

func (v NullableStoredMatchMetaMap) Get() *StoredMatchMetaMap {
	return v.value
}

func (v *NullableStoredMatchMetaMap) Set(val *StoredMatchMetaMap) {
	v.value = val
	v.isSet = true
}

func (v NullableStoredMatchMetaMap) IsSet() bool {
	return v.isSet
}

func (v *NullableStoredMatchMetaMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoredMatchMetaMap(val *StoredMatchMetaMap) *NullableStoredMatchMetaMap {
	return &NullableStoredMatchMetaMap{value: val, isSet: true}
}

func (v NullableStoredMatchMetaMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoredMatchMetaMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


