/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EsportsV2IdSlug type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EsportsV2IdSlug{}

// EsportsV2IdSlug struct for EsportsV2IdSlug
type EsportsV2IdSlug struct {
	Id int32 `json:"id"`
	Slug string `json:"slug"`
}

type _EsportsV2IdSlug EsportsV2IdSlug

// NewEsportsV2IdSlug instantiates a new EsportsV2IdSlug object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsportsV2IdSlug(id int32, slug string) *EsportsV2IdSlug {
	this := EsportsV2IdSlug{}
	this.Id = id
	this.Slug = slug
	return &this
}

// NewEsportsV2IdSlugWithDefaults instantiates a new EsportsV2IdSlug object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsportsV2IdSlugWithDefaults() *EsportsV2IdSlug {
	this := EsportsV2IdSlug{}
	return &this
}

// GetId returns the Id field value
func (o *EsportsV2IdSlug) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EsportsV2IdSlug) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EsportsV2IdSlug) SetId(v int32) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *EsportsV2IdSlug) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *EsportsV2IdSlug) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *EsportsV2IdSlug) SetSlug(v string) {
	o.Slug = v
}

func (o EsportsV2IdSlug) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EsportsV2IdSlug) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	return toSerialize, nil
}

func (o *EsportsV2IdSlug) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEsportsV2IdSlug := _EsportsV2IdSlug{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEsportsV2IdSlug)

	if err != nil {
		return err
	}

	*o = EsportsV2IdSlug(varEsportsV2IdSlug)

	return err
}

type NullableEsportsV2IdSlug struct {
	value *EsportsV2IdSlug
	isSet bool
}

func (v NullableEsportsV2IdSlug) Get() *EsportsV2IdSlug {
	return v.value
}

func (v *NullableEsportsV2IdSlug) Set(val *EsportsV2IdSlug) {
	v.value = val
	v.isSet = true
}

func (v NullableEsportsV2IdSlug) IsSet() bool {
	return v.isSet
}

func (v *NullableEsportsV2IdSlug) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsportsV2IdSlug(val *EsportsV2IdSlug) *NullableEsportsV2IdSlug {
	return &NullableEsportsV2IdSlug{value: val, isSet: true}
}

func (v NullableEsportsV2IdSlug) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsportsV2IdSlug) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


