/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchesV2Data type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchesV2Data{}

// MatchesV2Data struct for MatchesV2Data
type MatchesV2Data struct {
	Coaches []MatchesV2DataCoach `json:"coaches"`
	Kills []MatchesV2DataKill `json:"kills"`
	Metadata MatchesV2DataMetadata `json:"metadata"`
	Observers []MatchesV2DataObserver `json:"observers"`
	Players MatchesV2DataPlayers `json:"players"`
	Rounds []MatchesV2DataRound `json:"rounds"`
	Teams MatchesV2DataTeams `json:"teams"`
}

type _MatchesV2Data MatchesV2Data

// NewMatchesV2Data instantiates a new MatchesV2Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchesV2Data(coaches []MatchesV2DataCoach, kills []MatchesV2DataKill, metadata MatchesV2DataMetadata, observers []MatchesV2DataObserver, players MatchesV2DataPlayers, rounds []MatchesV2DataRound, teams MatchesV2DataTeams) *MatchesV2Data {
	this := MatchesV2Data{}
	this.Coaches = coaches
	this.Kills = kills
	this.Metadata = metadata
	this.Observers = observers
	this.Players = players
	this.Rounds = rounds
	this.Teams = teams
	return &this
}

// NewMatchesV2DataWithDefaults instantiates a new MatchesV2Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchesV2DataWithDefaults() *MatchesV2Data {
	this := MatchesV2Data{}
	return &this
}

// GetCoaches returns the Coaches field value
func (o *MatchesV2Data) GetCoaches() []MatchesV2DataCoach {
	if o == nil {
		var ret []MatchesV2DataCoach
		return ret
	}

	return o.Coaches
}

// GetCoachesOk returns a tuple with the Coaches field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetCoachesOk() ([]MatchesV2DataCoach, bool) {
	if o == nil {
		return nil, false
	}
	return o.Coaches, true
}

// SetCoaches sets field value
func (o *MatchesV2Data) SetCoaches(v []MatchesV2DataCoach) {
	o.Coaches = v
}

// GetKills returns the Kills field value
func (o *MatchesV2Data) GetKills() []MatchesV2DataKill {
	if o == nil {
		var ret []MatchesV2DataKill
		return ret
	}

	return o.Kills
}

// GetKillsOk returns a tuple with the Kills field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetKillsOk() ([]MatchesV2DataKill, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kills, true
}

// SetKills sets field value
func (o *MatchesV2Data) SetKills(v []MatchesV2DataKill) {
	o.Kills = v
}

// GetMetadata returns the Metadata field value
func (o *MatchesV2Data) GetMetadata() MatchesV2DataMetadata {
	if o == nil {
		var ret MatchesV2DataMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetMetadataOk() (*MatchesV2DataMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *MatchesV2Data) SetMetadata(v MatchesV2DataMetadata) {
	o.Metadata = v
}

// GetObservers returns the Observers field value
func (o *MatchesV2Data) GetObservers() []MatchesV2DataObserver {
	if o == nil {
		var ret []MatchesV2DataObserver
		return ret
	}

	return o.Observers
}

// GetObserversOk returns a tuple with the Observers field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetObserversOk() ([]MatchesV2DataObserver, bool) {
	if o == nil {
		return nil, false
	}
	return o.Observers, true
}

// SetObservers sets field value
func (o *MatchesV2Data) SetObservers(v []MatchesV2DataObserver) {
	o.Observers = v
}

// GetPlayers returns the Players field value
func (o *MatchesV2Data) GetPlayers() MatchesV2DataPlayers {
	if o == nil {
		var ret MatchesV2DataPlayers
		return ret
	}

	return o.Players
}

// GetPlayersOk returns a tuple with the Players field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetPlayersOk() (*MatchesV2DataPlayers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Players, true
}

// SetPlayers sets field value
func (o *MatchesV2Data) SetPlayers(v MatchesV2DataPlayers) {
	o.Players = v
}

// GetRounds returns the Rounds field value
func (o *MatchesV2Data) GetRounds() []MatchesV2DataRound {
	if o == nil {
		var ret []MatchesV2DataRound
		return ret
	}

	return o.Rounds
}

// GetRoundsOk returns a tuple with the Rounds field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetRoundsOk() ([]MatchesV2DataRound, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rounds, true
}

// SetRounds sets field value
func (o *MatchesV2Data) SetRounds(v []MatchesV2DataRound) {
	o.Rounds = v
}

// GetTeams returns the Teams field value
func (o *MatchesV2Data) GetTeams() MatchesV2DataTeams {
	if o == nil {
		var ret MatchesV2DataTeams
		return ret
	}

	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value
// and a boolean to check if the value has been set.
func (o *MatchesV2Data) GetTeamsOk() (*MatchesV2DataTeams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Teams, true
}

// SetTeams sets field value
func (o *MatchesV2Data) SetTeams(v MatchesV2DataTeams) {
	o.Teams = v
}

func (o MatchesV2Data) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchesV2Data) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["coaches"] = o.Coaches
	toSerialize["kills"] = o.Kills
	toSerialize["metadata"] = o.Metadata
	toSerialize["observers"] = o.Observers
	toSerialize["players"] = o.Players
	toSerialize["rounds"] = o.Rounds
	toSerialize["teams"] = o.Teams
	return toSerialize, nil
}

func (o *MatchesV2Data) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"coaches",
		"kills",
		"metadata",
		"observers",
		"players",
		"rounds",
		"teams",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchesV2Data := _MatchesV2Data{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchesV2Data)

	if err != nil {
		return err
	}

	*o = MatchesV2Data(varMatchesV2Data)

	return err
}

type NullableMatchesV2Data struct {
	value *MatchesV2Data
	isSet bool
}

func (v NullableMatchesV2Data) Get() *MatchesV2Data {
	return v.value
}

func (v *NullableMatchesV2Data) Set(val *MatchesV2Data) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchesV2Data) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchesV2Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchesV2Data(val *MatchesV2Data) *NullableMatchesV2Data {
	return &NullableMatchesV2Data{value: val, isSet: true}
}

func (v NullableMatchesV2Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchesV2Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


