/*
HenrikDev API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package henrikdevapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PremierTeamV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PremierTeamV1Response{}

// PremierTeamV1Response struct for PremierTeamV1Response
type PremierTeamV1Response struct {
	Data PremierTeamV1ResponseData `json:"data"`
	Status int32 `json:"status"`
}

type _PremierTeamV1Response PremierTeamV1Response

// NewPremierTeamV1Response instantiates a new PremierTeamV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPremierTeamV1Response(data PremierTeamV1ResponseData, status int32) *PremierTeamV1Response {
	this := PremierTeamV1Response{}
	this.Data = data
	this.Status = status
	return &this
}

// NewPremierTeamV1ResponseWithDefaults instantiates a new PremierTeamV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPremierTeamV1ResponseWithDefaults() *PremierTeamV1Response {
	this := PremierTeamV1Response{}
	return &this
}

// GetData returns the Data field value
func (o *PremierTeamV1Response) GetData() PremierTeamV1ResponseData {
	if o == nil {
		var ret PremierTeamV1ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PremierTeamV1Response) GetDataOk() (*PremierTeamV1ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PremierTeamV1Response) SetData(v PremierTeamV1ResponseData) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *PremierTeamV1Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PremierTeamV1Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PremierTeamV1Response) SetStatus(v int32) {
	o.Status = v
}

func (o PremierTeamV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PremierTeamV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PremierTeamV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPremierTeamV1Response := _PremierTeamV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPremierTeamV1Response)

	if err != nil {
		return err
	}

	*o = PremierTeamV1Response(varPremierTeamV1Response)

	return err
}

type NullablePremierTeamV1Response struct {
	value *PremierTeamV1Response
	isSet bool
}

func (v NullablePremierTeamV1Response) Get() *PremierTeamV1Response {
	return v.value
}

func (v *NullablePremierTeamV1Response) Set(val *PremierTeamV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePremierTeamV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePremierTeamV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePremierTeamV1Response(val *PremierTeamV1Response) *NullablePremierTeamV1Response {
	return &NullablePremierTeamV1Response{value: val, isSet: true}
}

func (v NullablePremierTeamV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePremierTeamV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


