/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.AccoladeKind

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bestValue 
 * @param count 
 * @param id 
 * @param type 
 */


data class AccoladesV1SummaryMetric (

    @Json(name = "best_value")
    val bestValue: kotlin.Double,

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "type")
    val type: AccoladeKind? = null

) {


}

