/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.AccoladesV1SeasonId
import henrikdevApiClient.models.AccoladesV1SummaryMetric

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accolades 
 * @param season 
 */


data class AccoladesV1Season (

    @Json(name = "accolades")
    val accolades: kotlin.collections.List<AccoladesV1SummaryMetric>,

    @Json(name = "season")
    val season: AccoladesV1SeasonId

) {


}

