/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param message 
 * @param status 
 * @param details 
 */


data class APIError (

    @Json(name = "code")
    val code: kotlin.Int,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "status")
    val status: kotlin.Int,

    @Json(name = "details")
    val details: kotlin.Any? = null

) {


}

