/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.EsportsV2IdSlug
import henrikdevApiClient.models.EsportsV2MatchLeague
import henrikdevApiClient.models.EsportsV2PlayerMatchTeam

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param league 
 * @param match 
 * @param teams 
 * @param vods 
 * @param date 
 */


data class EsportsV2PlayerMatch (

    @Json(name = "league")
    val league: EsportsV2MatchLeague,

    @Json(name = "match")
    val match: EsportsV2IdSlug,

    @Json(name = "teams")
    val teams: kotlin.collections.List<EsportsV2PlayerMatchTeam>,

    @Json(name = "vods")
    val vods: kotlin.collections.List<kotlin.String>,

    @Json(name = "date")
    val date: kotlin.String? = null

) {


}

