/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.EsportsV2PlayerPerformanceClutches
import henrikdevApiClient.models.EsportsV2PlayerPerformanceMultiKills
import henrikdevApiClient.models.EsportsV2PlayerPerformancePlayer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clutches 
 * @param defuses 
 * @param econRating 
 * @param multiKills 
 * @param plants 
 * @param player 
 */


data class EsportsV2PlayerPerformance (

    @Json(name = "clutches")
    val clutches: EsportsV2PlayerPerformanceClutches,

    @Json(name = "defuses")
    val defuses: kotlin.Int,

    @Json(name = "econ_rating")
    val econRating: kotlin.Int,

    @Json(name = "multi_kills")
    val multiKills: EsportsV2PlayerPerformanceMultiKills,

    @Json(name = "plants")
    val plants: kotlin.Int,

    @Json(name = "player")
    val player: EsportsV2PlayerPerformancePlayer

) {


}

