/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.EsportsV2EventType
import henrikdevApiClient.models.EsportsV2Region

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param region 
 * @param type 
 */


data class EsportsV2EventsQuery (

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "region")
    val region: EsportsV2Region? = null,

    @Json(name = "type")
    val type: EsportsV2EventType? = null

) {


}

