/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.EsportsV2TeamMatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param status 
 */


data class EsportsV2TeamMatchListResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<EsportsV2TeamMatch>,

    @Json(name = "status")
    val status: kotlin.Int

) {


}

