/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param acs 
 * @param adr 
 * @param apr 
 * @param assists 
 * @param deaths 
 * @param fdpr 
 * @param firstDeaths 
 * @param firstKills 
 * @param fkpr 
 * @param kast 
 * @param kd 
 * @param kills 
 * @param kpr 
 * @param rating 
 */


data class EsportsV2AgentPerformanceStats (

    @Json(name = "acs")
    val acs: kotlin.Float,

    @Json(name = "adr")
    val adr: kotlin.Float,

    @Json(name = "apr")
    val apr: kotlin.Float,

    @Json(name = "assists")
    val assists: kotlin.Int,

    @Json(name = "deaths")
    val deaths: kotlin.Int,

    @Json(name = "fdpr")
    val fdpr: kotlin.Float,

    @Json(name = "first_deaths")
    val firstDeaths: kotlin.Int,

    @Json(name = "first_kills")
    val firstKills: kotlin.Int,

    @Json(name = "fkpr")
    val fkpr: kotlin.Float,

    @Json(name = "kast")
    val kast: kotlin.Float,

    @Json(name = "kd")
    val kd: kotlin.Float,

    @Json(name = "kills")
    val kills: kotlin.Int,

    @Json(name = "kpr")
    val kpr: kotlin.Float,

    @Json(name = "rating")
    val rating: kotlin.Float

) {


}

