/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.Bundle

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bundle 
 * @param bundleRemainingDurationInSeconds 
 * @param bundles 
 */


data class FeaturedBundle (

    @Json(name = "Bundle")
    val bundle: Bundle,

    @Json(name = "BundleRemainingDurationInSeconds")
    val bundleRemainingDurationInSeconds: kotlin.Int,

    @Json(name = "Bundles")
    val bundles: kotlin.collections.List<Bundle>

) {


}

