/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.LeaderboardPVPPlayer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param immortal1Threshold 
 * @param immortal2Threshold 
 * @param immortal3Threshold 
 * @param lastUpdate 
 * @param nextUpdate 
 * @param players 
 * @param radiantThreshold 
 * @param totalPlayers 
 */


data class LeaderboardV2Response (

    @Json(name = "immortal_1_threshold")
    val immortal1Threshold: kotlin.Int,

    @Json(name = "immortal_2_threshold")
    val immortal2Threshold: kotlin.Int,

    @Json(name = "immortal_3_threshold")
    val immortal3Threshold: kotlin.Int,

    @Json(name = "last_update")
    val lastUpdate: kotlin.Long,

    @Json(name = "next_update")
    val nextUpdate: kotlin.Long,

    @Json(name = "players")
    val players: kotlin.collections.List<LeaderboardPVPPlayer>,

    @Json(name = "radiant_threshold")
    val radiantThreshold: kotlin.Int,

    @Json(name = "total_players")
    val totalPlayers: kotlin.Int

) {


}

