/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.MatchesV2DataPlayer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allPlayers 
 * @param blue 
 * @param red 
 */


data class MatchesV2DataPlayers (

    @Json(name = "all_players")
    val allPlayers: kotlin.collections.List<MatchesV2DataPlayer>,

    @Json(name = "blue")
    val blue: kotlin.collections.List<MatchesV2DataPlayer>,

    @Json(name = "red")
    val red: kotlin.collections.List<MatchesV2DataPlayer>

) {


}

