/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param average 
 * @param overall 
 */


data class MatchesV4DataPlayerEconomyLoadoutValue (

    @Json(name = "average")
    val average: kotlin.Float,

    @Json(name = "overall")
    val overall: kotlin.Int

) {


}

