/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.MatchesV2DataPlayerAssetsAgent
import henrikdevApiClient.models.MatchesV2DataPlayerAssetsCard

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param agent 
 * @param card 
 */


data class MatchesV2DataPlayerAssets (

    @Json(name = "agent")
    val agent: MatchesV2DataPlayerAssetsAgent,

    @Json(name = "card")
    val card: MatchesV2DataPlayerAssetsCard

) {


}

