/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param card 
 * @param title 
 * @param preferredLevelBorder 
 */


data class MatchesV4DataPlayerCustomization (

    @Json(name = "card")
    val card: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "preferred_level_border")
    val preferredLevelBorder: kotlin.String? = null

) {


}

