/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param after 
 * @param before 
 * @param returned 
 * @param total 
 */


data class Pagination (

    @Json(name = "after")
    val after: kotlin.Int,

    @Json(name = "before")
    val before: kotlin.Int,

    @Json(name = "returned")
    val returned: kotlin.Int,

    @Json(name = "total")
    val total: kotlin.Int

) {


}

