/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.PremiumWebhookEvent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Tracked user. Missing last_match, last_mmr and last_checked_at are serialized as null, not omitted. last_match is the polling marker as a string of Unix milliseconds, not a match UUID. last_checked_at, created_at and updated_at are Unix seconds.
 *
 * @param createdAt 
 * @param enabled 
 * @param events 
 * @param id 
 * @param lastCheckedAt 
 * @param lastMatch 
 * @param lastMmr 
 * @param puuid 
 * @param region 
 * @param updatedAt 
 */


data class PremiumWebhookUserResponse (

    @Json(name = "created_at")
    val createdAt: kotlin.Long,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "events")
    val events: kotlin.collections.List<PremiumWebhookEvent>,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "last_checked_at")
    val lastCheckedAt: kotlin.Long?,

    @Json(name = "last_match")
    val lastMatch: kotlin.String?,

    @Json(name = "last_mmr")
    val lastMmr: kotlin.Int?,

    @Json(name = "puuid")
    val puuid: java.util.UUID,

    @Json(name = "region")
    val region: kotlin.String,

    @Json(name = "updated_at")
    val updatedAt: kotlin.Long

) {


}

