/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.PremierTeamMember
import henrikdevApiClient.models.PremierTeamV1ResponseDataCustomization
import henrikdevApiClient.models.PremierTeamV1ResponseDataPlacement
import henrikdevApiClient.models.PremierTeamV1ResponseDataStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param customization 
 * @param enrolled 
 * @param id 
 * @param member 
 * @param name 
 * @param placement 
 * @param stats 
 * @param tag 
 */


data class PremierTeamV1ResponseData (

    @Json(name = "customization")
    val customization: PremierTeamV1ResponseDataCustomization,

    @Json(name = "enrolled")
    val enrolled: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "member")
    val member: kotlin.collections.List<PremierTeamMember>,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "placement")
    val placement: PremierTeamV1ResponseDataPlacement,

    @Json(name = "stats")
    val stats: PremierTeamV1ResponseDataStats,

    @Json(name = "tag")
    val tag: kotlin.String

) {


}

