/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxPartySize 
 * @param maxTier 
 * @param minTier 
 */


data class QueueStatusV1HighSkill (

    @Json(name = "max_party_size")
    val maxPartySize: kotlin.Int,

    @Json(name = "max_tier")
    val maxTier: kotlin.Int,

    @Json(name = "min_tier")
    val minTier: kotlin.Int

) {


}

