/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package henrikdevApiClient.models

import henrikdevApiClient.models.RawV1PayloadValues
import henrikdevApiClient.models.RawV1ResourceType
import henrikdevApiClient.models.ValorantAffinity
import henrikdevApiClient.models.ValorantPlatform

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Raw Riot request. Resource names are case-sensitive. Region and platform are case-insensitive; platform defaults to pc. Matchdetails accepts one or multiple match UUIDs, ignores queries, and returns an object for one result or an array for multiple results. Other resources use a player UUID (only the first array entry) and forward queries unchanged; include the leading ? when supplying a query string.
 *
 * @param region 
 * @param type 
 * @param `value` 
 * @param platform 
 * @param queries 
 */


data class RawV1Payload (

    @Json(name = "region")
    val region: ValorantAffinity,

    @Json(name = "type")
    val type: RawV1ResourceType,

    @Json(name = "value")
    val `value`: RawV1PayloadValues,

    @Json(name = "platform")
    val platform: ValorantPlatform? = null,

    @Json(name = "queries")
    val queries: kotlin.String? = null

) {


}

