/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package henrikdevApiClient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param made 
 * @param received 
 */


data class StoredMatchStatsDamage (

    @Json(name = "made")
    val made: kotlin.Int,

    @Json(name = "received")
    val received: kotlin.Int

) {


}

